using Cms360.Common;
using Cms360.Contract;
using Cms360.Contract.Security;
using Cms360.Data.Model;
using Cms360.Service.Security;
using StructureMap;

namespace Cms360.Service
{
    public class ContainerRegistry : Registry
    {
        public ContainerRegistry()
        {
            For<ICryptoService>().Use<CryptoHelper>();

            For<ILocalAuthenticationService>().Use<LocalAuthenticationService>();
            For<IExternalAuthenticationService>().Use<ExternalAuthenticationService>();
            For<IExternalAuthenticationProvider>().Add<GoogleAuthenticationProvider>();
            For<IExternalAuthenticationProvider>().Add<MicrosoftAuthenticationProvider>();


            For<ILevelProgramClassMapRepository>().Use<LevelProgramClassMapRepository>();
            For<IVWLevelProgramClassMapRepository>().Use<VWLevelProgramClassMapRepository>();
            For<IAssessmentSectionMapRepository>().Use<AssessmentSectionMapRepository>();
            For<IVWAssessmentSectionMapRepository>().Use<VWAssessmentSectionMapRepository>();


            For<IAuditService>().Use<AuditService>();
            For<IManageRoleService>().Use<ManageRoleService>();
            For<IManageProfileService>().Use<ManageUserService>();
            For<IManageUserService>().Use<ManageUserService>();
            For<ISecurityClaimsInspector>().Use<SecurityClaimsInspector>().Singleton();
            For<ISignupService>().Use<SignupService>();
            For<ITokenProviderService<Token>>().Use<TokenProviderService>();
            For<IRegistrationCourseRepository>().Use<RegistrationCourseRepository>();
            For<ICampusEmailMappingRepository>().Use<CampusEmailMappingRepository>();
            For<IRegistrationEnrollmentsRepository>().Use<RegistrationEnrollmentsRepository>();
            For<IRegistrationProgramCourseLinkRepository>().Use<RegistrationProgramCourseLinkRepository>();
            For<IRegistrationSectionCourseLinkRepository>().Use<RegistrationSectionCourseLinkRepository>();
            For<IRegistrationSectionCourseLinkVMRepository>().Use<RegistrationSectionCourseLinkVMRepository>();
            For<IRegistrationSectionsRepository>().Use<RegistrationSectionsRepository>();
            For<ISetupAddressRepository>().Use<SetupAddressRepository>();
            For<ISetupBatchRepository>().Use<SetupBatchRepository>();
            For<ISetupDegreeRepository>().Use<SetupDegreeRepository>();
            For<ISetupGroupRepository>().Use<SetupGroupRepository>();
            For<ISetupPassStatusRepository>().Use<SetupPassStatusRepository>();
            For<ISetupAdmissionTypeRepository>().Use<SetupAdmissionTypeRepository>();
            For<ISetupBloodGroupRepository>().Use<SetupBloodGroupRepository>();
            For<ISetupBoardRepository>().Use<SetupBoardRepository>();
            For<ISessionBoardFeeRepository>().Use<SessionBoardFeeRepository>();
            For<IBoardFeeRepository>().Use<BoardFeeRepository>();
            For<IBoardRegistrationCodeRepository>().Use<BoardRegistrationCodeRepository>();
            For<IBoardExamTypeRepository>().Use<BoardExamTypeRepository>();
            For<ILevelDefinitionRepository>().Use<LevelDefinitionRepository>();
            For<IBoardStudentBoardLinkRepository>().Use<BoardStudentBoardLinkRepository>();
            For<ISetupBoardTypeRepository>().Use<SetupBoardTypeRepository>();
            For<ISetupBuildingRepository>().Use<SetupBuildingRepository>();
            For<ISetupBuildingAddressLinkRepository>().Use<SetupBuildingAddressLinkRepository>();
            For<ISetupBusinessGroupRepository>().Use<SetupBusinessGroupRepository>();
            For<ISetupBusinessUnitRepository>().Use<SetupBusinessUnitRepository>();
            For<ISetupCampusRepository>().Use<SetupCampusRepository>();
            For<ISetupCampusBuildingLinkRepository>().Use<SetupCampusBuildingLinkRepository>();
            For<ISetupCampusProgramLinkRepository>().Use<SetupCampusProgramLinkRepository>();
            For<ISetupCityRepository>().Use<SetupCityRepository>();
            For<ISetupClassRepository>().Use<SetupClassRepository>();
            For<ISetupCollectorRepository>().Use<SetupCollectorRepository>();
            For<ISetupCountryRepository>().Use<SetupCountryRepository>();
            For<ISetupGenderRepository>().Use<SetupGenderRepository>();
            For<ISetupInstitutionRepository>().Use<SetupInstitutionRepository>();
            For<ISetupInstitutionTypeRepository>().Use<SetupInstitutionTypeRepository>();
            For<ISetupMediumRepository>().Use<SetupMediumRepository>();
            For<ISetupConcessionRemarksRepository>().Use<SetupConcessionRemarksRepository>();
            For<ISetupVWConcessionRemarksVMRepository>().Use<SetupVWConcessionRemarksVMRepository>();
            For<ISetupMonthRepository>().Use<SetupMonthRepository>();
            For<IDayOffRepository>().Use<DayOffRepository>();
            For<IDayOffVMRepository>().Use<DayOffVMRepository>();
            For<ISetupNationalityRepository>().Use<SetupNationalityRepository>();
            For<ISetupPossessionRepository>().Use<SetupPossessionRepository>();
            For<ISetupPossessionTypeRepository>().Use<SetupPossessionTypeRepository>();
            For<ISetupPossessionVMRepository>().Use<SetupPossessionVMRepository>();
            For<ISetupProgramRepository>().Use<SetupProgramRepository>();
            For<ISetupCampusBaseProgramRepository>().Use<SetupCampusBaseProgramRepository>();
            For<ISetupProgramDetailsRepository>().Use<SetupProgramDetailsRepository>();
            For<ISetupProvinceRepository>().Use<SetupProvinceRepository>();
            For<ISetupReligionRepository>().Use<SetupReligionRepository>();
            For<ISetupRoomRepository>().Use<SetupRoomRepository>();
            For<ISetupRoomBuildingLinkRepository>().Use<SetupRoomBuildingLinkRepository>();
            For<ISetupRoomTypeRepository>().Use<SetupRoomTypeRepository>();
            For<ISetupSectionRepository>().Use<SetupSectionRepository>();
            For<ISetupSessionRepository>().Use<SetupSessionRepository>();
            For<ISetupShiftRepository>().Use<SetupShiftRepository>();
            For<ITimeTableSlotsRepositoryVM>().Use<TimeTableSlotsRepositoryVM>();
            For<ITimeTableTimeTableTeacherRepository>().Use<TimeTableTimeTableTeacherRepository>();
            For<ISetupStatusRepository>().Use<SetupStatusRepository>();
            For<ISetupTermRepository>().Use<SetupTermRepository>();
            For<ISetupZoneRepository>().Use<SetupZoneRepository>();
            For<ISetupZoneCityLinkRepository>().Use<SetupZoneCityLinkRepository>();
            For<ITimeTableSlotsRepository>().Use<TimeTableSlotsRepository>();
            For<IMinimumPaidDateRepository>().Use<MinimumPaidDateRepository>();
            For<IReturnTypeRepository>().Use<ReturnTypeRepository>();
            For<ITimeTableSlotTimingsRepository>().Use<TimeTableSlotTimingsRepository>();
            For<ITimeTableVWSlotTimingsRepository>().Use<TimeTableVWSlotTimingsRepository>();
            For<ITimeTableTimeTableRepository>().Use<TimeTableTimeTableRepository>();
            For<ISetupProvinceVMRepository>().Use<SetupProvinceVMRepository>();
            For<IPublicVWDashBoardVMRepository>().Use<PublicVWDashBoardVMRepository>();
            For<IPublicStudentFeeCountVMRepository>().Use<PublicStudentFeeCountVMRepository>();
            For<IVWConcessionRepository>().Use<VWConcessionRepository>();
            For<ISetupBuildingAddressPossessionVMRepository>().Use<SetupBuildingAddressPossessionVMRepository>();
            For<ISetupTermSessionVMRepository>().Use<SetupTermSessionVMRepository>();
            For<IAdmissionBulitanSaleRepository>().Use<AdmissionBulitanSaleRepository>();
            For<IAdmissionInquiryRepository>().Use<AdmissionInquiryRepository>();
            For<IStruckoffReinstateRepository>().Use<StruckoffReinstateRepository>();
            For<IAdmissionEligibilityCriteriaRepository>().Use<AdmissionEligibilityCriteriaRepository>();
            For<IAdmissionSaleTypeRepository>().Use<AdmissionSaleTypeRepository>();
            For<IAdmissionStudentsRepository>().Use<AdmissionStudentsRepository>();
            For<IAdmissionStudentsImageRepository>().Use<AdmissionStudentsImageRepository>();
            For<IAttendanceAttendanceDetailRepository>().Use<AttendanceAttendanceDetailRepository>();
            For<IAttendanceAttendenceMasterRepository>().Use<AttendanceAttendenceMasterRepository>();
            For<IAttendanceAttendenceStatusRepository>().Use<AttendanceAttendenceStatusRepository>();
            For<IMinimumLeavePolicyRepository>().Use<MinimumLeavePolicyRepository>();
            For<IExaminationCampusGradingPolicyLinkRepository>().Use<ExaminationCampusGradingPolicyLinkRepository>();
            For<IExaminationCampusFailCriteriaMappingRepository>().Use<ExaminationCampusFailCriteriaMappingRepository>();
            For<IExaminationVWFailMasterCriteriaRepository>().Use<ExaminationVWFailMasterCriteriaRepository>();
            For<IExaminationCampusGradingMappingRepository>().Use<ExaminationCampusGradingMappingRepository>();
            For<IExaminationExamDetailRepository>().Use<ExaminationExamDetailRepository>();
            For<IExamDataVMRepository>().Use<ExamDataVMRepository>();
            For<IExaminationExamMasterRepository>().Use<ExaminationExamMasterRepository>();
            For<IExaminationExamMasterRepositoryVM>().Use<ExaminationExamMasterRepositoryVM>();
            For<IExaminationExamTypeRepository>().Use<ExaminationExamTypeRepository>();
            For<IExaminationGradingPolicyRepository>().Use<ExaminationGradingPolicyRepository>();
            For<IExaminationFailCriteriaRepository>().Use<ExaminationFailCriteriaRepository>();
            For<IExaminationFailMasterCriteriaRepository>().Use<ExaminationFailMasterCriteriaRepository>();
            For<IExaminationFailDetailCriteriaRepository>().Use<ExaminationFailDetailCriteriaRepository>();
            For<IExaminationGradingCriteriaVMRepository>().Use<ExaminationGradingCriteriaVMRepository>();
            For<IExaminationGradingDetailRepository>().Use<ExaminationGradingDetailRepository>();
            For<IExaminationGradingMasterRepository>().Use<ExaminationGradingMasterRepository>();
            For<IFeeBankRepository>().Use<FeeBankRepository>();
            For<IFeeBankRepositoryVM>().Use<FeeBankRepositoryVM>();
            For<IFeeCampusBankLinkRepository>().Use<FeeCampusBankLinkRepository>();
            For<IRolePrevilagesRepository>().Use<RolePrevilagesRepository>();
            For<IRoleUserLogRepository>().Use<RoleUserLogRepository>();
            For<IRoleSecurityClaimUpdRepository>().Use<RoleSecurityClaimUpdRepository>();
            For<IFeeCampusChallanNoteLinkRepository>().Use<FeeCampusChallanNoteLinkRepository>();
            For<IFeeChallanNoteRepository>().Use<FeeChallanNoteRepository>();
            For<IFeeChallanTypeRepository>().Use<FeeChallanTypeRepository>();
            For<IFeeChallanValidityRepository>().Use<FeeChallanValidityRepository>();
            For<IFeeConcessionRepository>().Use<FeeConcessionRepository>();
            For<IFeeConcessionDetailRepository>().Use<FeeConcessionDetailRepository>();
            For<IFeeConcessionDetailRepositoryVM>().Use<FeeConcessionDetailRepositoryVM>();
            For<IFeeContinuationPolicyRepository>().Use<FeeContinuationPolicyRepository>();
            For<IFeeFeeActivityRepository>().Use<FeeFeeActivityRepository>();
            For<IFeeFeeHeadRepository>().Use<FeeFeeHeadRepository>();
            For<IFeeFeeStructureRepository>().Use<FeeFeeStructureRepository>();
            For<IFeeFeeStructureDetailRepository>().Use<FeeFeeStructureDetailRepository>();
            For<IFeeFeeStructureDetailRepositoryVM>().Use<FeeFeeStructureDetailRepositoryVM>();
            For<IFeeScholarshipCriteriaRepository>().Use<FeeScholarshipCriteriaRepository>();
            For<IFeeStudentChallanRepository>().Use<FeeStudentChallanRepository>();
            For<IFeeStudentFeeStructureRepository>().Use<FeeStudentFeeStructureRepository>();
            For<IHumanResourceDesignationsRepository>().Use<HumanResourceDesignationsRepository>();
            For<IHumanResourceStaffRepository>().Use<HumanResourceStaffRepository>();
            For<IRegistrationCourseRepository>().Use<RegistrationCourseRepository>();
            For<IRegistrationEnrollmentsRepository>().Use<RegistrationEnrollmentsRepository>();
            For<IRegistrationProgramCourseLinkRepository>().Use<RegistrationProgramCourseLinkRepository>();
            For<IRegistrationSectionCourseLinkRepository>().Use<RegistrationSectionCourseLinkRepository>();
            For<IRegistrationSectionsRepository>().Use<RegistrationSectionsRepository>();
            For<ISetupAddressRepository>().Use<SetupAddressRepository>();
            For<ISetupAdmissionTypeRepository>().Use<SetupAdmissionTypeRepository>();
            For<ISetupBloodGroupRepository>().Use<SetupBloodGroupRepository>();
            For<ISetupBoardRepository>().Use<SetupBoardRepository>();
            For<ISetupBoardTypeRepository>().Use<SetupBoardTypeRepository>();
            For<ISetupBuildingRepository>().Use<SetupBuildingRepository>();
            For<ISetupBuildingAddressLinkRepository>().Use<SetupBuildingAddressLinkRepository>();
            For<ISetupBusinessGroupRepository>().Use<SetupBusinessGroupRepository>();
            For<ISetupBusinessUnitRepository>().Use<SetupBusinessUnitRepository>();
            For<ISetupCampusRepository>().Use<SetupCampusRepository>();
            For<ISetupCampusBuildingLinkRepository>().Use<SetupCampusBuildingLinkRepository>();
            For<ISetupCampusBuildingLinkVMRepository>().Use<SetupCampusBuildingLinkVMRepository>();
            For<ISetupCampusProgramLinkRepository>().Use<SetupCampusProgramLinkRepository>();
            For<ISetupCityRepository>().Use<SetupCityRepository>();
            For<ISetupClassRepository>().Use<SetupClassRepository>();
            For<IAcademicCalendarTypeRepository>().Use<AcademicCalendarTypeRepository>();
            For<IEventsRepository>().Use<EventsRepository>();
            For<ISetupFranchiseRepository>().Use<SetupFranchiseRepository>();
            For<ISetupCollectorRepository>().Use<SetupCollectorRepository>();
            For<ISetupCountryRepository>().Use<SetupCountryRepository>();
            For<ISetupGenderRepository>().Use<SetupGenderRepository>();
            For<ISetupInstitutionRepository>().Use<SetupInstitutionRepository>();
            For<ISetupInstitutionTypeRepository>().Use<SetupInstitutionTypeRepository>();
            For<ISetupMediumRepository>().Use<SetupMediumRepository>();
            For<ISetupNationalityRepository>().Use<SetupNationalityRepository>();
            For<ISetupPossessionRepository>().Use<SetupPossessionRepository>();
            For<ISetupPossessionTypeRepository>().Use<SetupPossessionTypeRepository>();
            For<ISetupProgramRepository>().Use<SetupProgramRepository>();
            For<ISetupProgramDetailsRepository>().Use<SetupProgramDetailsRepository>();
            For<ISetupProvinceRepository>().Use<SetupProvinceRepository>();
            For<ISetupReligionRepository>().Use<SetupReligionRepository>();
            For<ISetupRoomRepository>().Use<SetupRoomRepository>();
            For<ISetupRoomBuildingLinkRepository>().Use<SetupRoomBuildingLinkRepository>();
            For<ISetupRoomTypeRepository>().Use<SetupRoomTypeRepository>();
            For<ISetupSectionRepository>().Use<SetupSectionRepository>();
            For<ISetupSessionRepository>().Use<SetupSessionRepository>();
            For<ISetupShiftRepository>().Use<SetupShiftRepository>();
            For<ISetupStatusRepository>().Use<SetupStatusRepository>();
            For<ISetupTermRepository>().Use<SetupTermRepository>();
            For<ISetupZoneRepository>().Use<SetupZoneRepository>();
            For<ISetupZoneCityLinkRepository>().Use<SetupZoneCityLinkRepository>();
            For<ITimeTableSlotsRepository>().Use<TimeTableSlotsRepository>();
            For<ITimeTableSlotTimingsRepository>().Use<TimeTableSlotTimingsRepository>();

            For<IDashboardSurveyMasterRepository>().Use<DashboardSurveyMasterRepository>();
            For<IDashboardSurveyDetailRepository>().Use<DashboardSurveyDetailRepository>();
            For<IAcademicCalendarRepository>().Add<AcademicCalendarRepository>();
             For<IAssessmentCategoryRepository>().Add<AssessmentCategoryRepository>();
               For<IAssessmentScheduleRepository>().Add<AssessmentScheduleRepository>();
            For<ICalendarExamTypeRepository>().Add<CalendarExamTypeRepository>();
            For<IAcademicCalendarTypeRepository>().Add<AcademicCalendarTypeRepository>();


            For<ISessionDurationRepository>().Use<SessionDurationRepository>();
            For<IVWSessionDurationRepository>().Use<VWSessionDurationRepository>();

            // For<ITimeTableTimeTableRepository>().Use<TimeTableTimeTableRepository>();
            For<ITimeTableTimeTableRepositoryVM>().Use<TimeTableTimeTableRepositoryVM>();
            For<ISetupProvinceVMRepository>().Use<SetupProvinceVMRepository>();
            For<ISetupBuildingAddressPossessionVMRepository>().Use<SetupBuildingAddressPossessionVMRepository>();
            For<ISetupRoomVMRepository>().Use<SetupRoomVMRepository>();
            For<ISetupInstitutionVMRepository>().Use<SetupInstitutionVMRepository>();
            For<IFeeCampusBankLinkVMRepository>().Use<FeeCampusBankLinkVMRepository>();
            For<IFeeChallanValidityVMRepository>().Use<FeeChallanValidityVMRepository>();
            For<IFeeConcessionVMRepository>().Use<FeeConcessionVMRepository>();
            For<IAdmissionEligibilityCriteriaVMRepository>().Use<AdmissionEligibilityCriteriaVMRepository>();
            For<IFeeCampusChallanNoteLinkVMRepository>().Use<FeeCampusChallanNoteLinkVMRepository>();
            For<ITimeTableSlotTimingsVMRepository>().Use<TimeTableSlotTimingsVMRepository>();
            For<IRegistrationProgramCourseLinkVMRepository>().Use<RegistrationProgramCourseLinkVMRepository>();
            For<IAdmissionStudentsImageVMRepository>().Use<AdmissionStudentsImageVMRepository>();
            For<IExaminationExamDetailRepository>().Use<ExaminationExamDetailRepository>();
            For<IExaminationExamDetailVMRepository>().Use<ExaminationExamDetailVMRepository>();
            For<IAttendanceAttendenceMasterVMRepository>().Use<AttendanceAttendenceMasterVMRepository>();
            For<IAttendanceAttendanceDetailVMRepository>().Use<AttendanceAttendanceDetailVMRepository>();
            For<IAdmissionAdmissionFormRepository>().Use<AdmissionAdmissionFormRepository>();
            For<IAssessmentTypeRepositoryVM>().Use<AssessmentTypeRepositoryVM>();

            For<IAssessmentTypeRepository>().Use<AssessmentTypeRepository>();
            For<IAssessmentTypeRepositoryEx>().Use<AssessmentTypeRepositoryEx>();
            For<IAssessmentSchemeMasterRepository>().Use<AssessmentSchemeMasterRepository>();
            For<IAssessmentSchemeDetailRepository>().Use<AssessmentSchemeDetailRepository>();
            For<IAssessmentSchemeMasterRepositoryVM>().Use<AssessmentSchemeMasterRepositoryVM>();





            For<IAdmissionBulitanSaleRepository>().Use<AdmissionBulitanSaleRepository>();
            For<IAdmissionEligibilityCriteriaRepository>().Use<AdmissionEligibilityCriteriaRepository>();
            For<IAdmissionSaleTypeRepository>().Use<AdmissionSaleTypeRepository>();
            For<IAdmissionStudentsRepository>().Use<AdmissionStudentsRepository>();
            For<IAdmissionStudentsImageRepository>().Use<AdmissionStudentsImageRepository>();
            For<IAttendanceAttendanceDetailRepository>().Use<AttendanceAttendanceDetailRepository>();
            For<IAttendanceAttendenceMasterRepository>().Use<AttendanceAttendenceMasterRepository>();
            For<IAttendanceAttendenceStatusRepository>().Use<AttendanceAttendenceStatusRepository>();
            For<IBoardBoardCampusRepository>().Use<BoardBoardCampusRepository>();
            For<IBoardCampusStudentLinkRepository>().Use<BoardCampusStudentLinkRepository>();
            For<IExaminationCampusGradingPolicyLinkRepository>().Use<ExaminationCampusGradingPolicyLinkRepository>();
            For<IExaminationExamDetailRepository>().Use<ExaminationExamDetailRepository>();
            For<IExaminationExamSectionLinkVMRepository>().Use<ExaminationExamSectionLinkVMRepository>();
            For<IExaminationExamMasterRepository>().Use<ExaminationExamMasterRepository>();
            For<IExaminationExamTypeRepository>().Use<ExaminationExamTypeRepository>();
            For<IExaminationGradingPolicyRepository>().Use<ExaminationGradingPolicyRepository>();
            For<IExaminationExamScheduleRepository>().Use<ExaminationExamScheduleRepository>();
            For<IExaminationExamScheduleVMRepository>().Use<ExaminationExamScheduleVMRepository>();
            For<IFeeBankRepository>().Use<FeeBankRepository>();
            For<IFeeCampusBankLinkRepository>().Use<FeeCampusBankLinkRepository>();
            For<IFeeCampusChallanNoteLinkRepository>().Use<FeeCampusChallanNoteLinkRepository>();
            For<IFeeChallanNoteRepository>().Use<FeeChallanNoteRepository>();
            For<IFeeChallanTypeRepository>().Use<FeeChallanTypeRepository>();
            For<IProgramFeeAdjustmentRepository>().Use<ProgramFeeAdjustmentRepository>();
            For<IEmailTemplateRepository>().Use<EmailTemplateRepository>();

            For<IFeeChallanValidityRepository>().Use<FeeChallanValidityRepository>();
            For<IFeeConcessionRepository>().Use<FeeConcessionRepository>();
            For<IFeeConcessionDetailRepository>().Use<FeeConcessionDetailRepository>();
            For<IFeeContinuationPolicyRepository>().Use<FeeContinuationPolicyRepository>();
            For<IFeeFeeActivityRepository>().Use<FeeFeeActivityRepository>();
            For<IFeeFeeHeadRepository>().Use<FeeFeeHeadRepository>();
            For<IFeeFeeStructureRepository>().Use<FeeFeeStructureRepository>();
            For<IFeeFeeStructureDetailRepository>().Use<FeeFeeStructureDetailRepository>();
            For<IFeeScholarshipCriteriaRepository>().Use<FeeScholarshipCriteriaRepository>();
            For<IFeeTBLGradesRepository>().Use<FeeTBLGradesRepository>();
            // For<IFeeStudentChallanRepository>().Use<FeeStudentChallanRepository>();
            For<IFeeStudentFeeStructureRepository>().Use<FeeStudentFeeStructureRepository>();
            For<IHumanResourceDepartmentsRepository>().Use<HumanResourceDepartmentsRepository>();
            For<IHumanResourceDepartmentsRepositoryVM>().Use<HumanResourceDepartmentsRepositoryVM>();

            For<IHumanResourceDesignationsRepository>().Use<HumanResourceDesignationsRepository>();
            For<IHumanResourceStaffRepository>().Use<HumanResourceStaffRepository>();
            For<IHumanResourceStaffRepositoryVM>().Use<HumanResourceStaffRepositoryVM>();
            For<IRegistrationCourseRepository>().Use<RegistrationCourseRepository>();
            For<IRegistrationEmailProgramRepository>().Use<RegistrationEmailProgramRepository>();

            For<IRegistrationEnrollmentsRepository>().Use<RegistrationEnrollmentsRepository>();
            For<IRegistrationProgramCourseLinkRepository>().Use<RegistrationProgramCourseLinkRepository>();
            For<IRegistrationSectionCourseLinkRepository>().Use<RegistrationSectionCourseLinkRepository>();
           // For<IRegistrationSectionCourseLinkVMRepository>().Use<RegistrationSectionCourseLinkVMRepository>();
            For<IRegistrationSectionsRepository>().Use<RegistrationSectionsRepository>();
            For<ISetupAddressRepository>().Use<SetupAddressRepository>();
            For<ISetupDegreeRepository>().Use<SetupDegreeRepository>();
            For<ISetupGroupRepository>().Use<SetupGroupRepository>();
            For<ISetupPassStatusRepository>().Use<SetupPassStatusRepository>();
            For<ISetupAdmissionTypeRepository>().Use<SetupAdmissionTypeRepository>();
            For<ISetupBloodGroupRepository>().Use<SetupBloodGroupRepository>();
            For<ISetupBoardRepository>().Use<SetupBoardRepository>();
            For<ISetupBoardTypeRepository>().Use<SetupBoardTypeRepository>();
            For<ISetupBuildingRepository>().Use<SetupBuildingRepository>();
            For<ISetupBuildingAddressLinkRepository>().Use<SetupBuildingAddressLinkRepository>();
            For<ISetupBusinessGroupRepository>().Use<SetupBusinessGroupRepository>();
            For<ISetupBusinessUnitRepository>().Use<SetupBusinessUnitRepository>();
            For<ISetupCampusRepository>().Use<SetupCampusRepository>();
            For<ISetupCampusBuildingLinkRepository>().Use<SetupCampusBuildingLinkRepository>();
            For<ISetupCampusProgramLinkRepository>().Use<SetupCampusProgramLinkRepository>();
            For<ISetupCityRepository>().Use<SetupCityRepository>();
            For<ISetupClassRepository>().Use<SetupClassRepository>();
            For<ISetupCollectorRepository>().Use<SetupCollectorRepository>();
            For<ISetupCountryRepository>().Use<SetupCountryRepository>();
            For<ISetupGenderRepository>().Use<SetupGenderRepository>();
            For<ISetupInstitutionRepository>().Use<SetupInstitutionRepository>();
            For<ISetupInstitutionTypeRepository>().Use<SetupInstitutionTypeRepository>();
            For<ISetupMediumRepository>().Use<SetupMediumRepository>();
            For<ISetupNationalityRepository>().Use<SetupNationalityRepository>();
            For<ISetupPossessionRepository>().Use<SetupPossessionRepository>();
            For<ISetupPossessionTypeRepository>().Use<SetupPossessionTypeRepository>();
            For<ISetupPossessionVMRepository>().Use<SetupPossessionVMRepository>();
            For<ISetupProgramRepository>().Use<SetupProgramRepository>();
            For<ISetupProgramDetailsRepository>().Use<SetupProgramDetailsRepository>();
            For<ISetupProvinceRepository>().Use<SetupProvinceRepository>();
            For<ISetupReligionRepository>().Use<SetupReligionRepository>();
            For<ISetupRoomRepository>().Use<SetupRoomRepository>();
            For<ISetupRoomBuildingLinkRepository>().Use<SetupRoomBuildingLinkRepository>();
            For<ISetupRoomTypeRepository>().Use<SetupRoomTypeRepository>();
            For<ISetupSectionRepository>().Use<SetupSectionRepository>();
            For<ISetupSessionRepository>().Use<SetupSessionRepository>();
            For<ISetupShiftRepository>().Use<SetupShiftRepository>();
            For<ITimeTableSlotsRepositoryVM>().Use<TimeTableSlotsRepositoryVM>();
            For<ISetupStatusRepository>().Use<SetupStatusRepository>();
            For<ISetupTermRepository>().Use<SetupTermRepository>();
            For<ISetupZoneRepository>().Use<SetupZoneRepository>();
            For<ISetupZoneCityLinkRepository>().Use<SetupZoneCityLinkRepository>();
            For<ITimeTableSlotsRepository>().Use<TimeTableSlotsRepository>();
            For<ITimeTableSlotTimingsRepository>().Use<TimeTableSlotTimingsRepository>();
            // For<ITimeTableTimeTableRepository>().Use<TimeTableTimeTableRepository>();
            For<ISetupProvinceVMRepository>().Use<SetupProvinceVMRepository>();
            For<ISetupBuildingAddressPossessionVMRepository>().Use<SetupBuildingAddressPossessionVMRepository>();
            For<ISetupTermSessionVMRepository>().Use<SetupTermSessionVMRepository>();
            For<IAdmissionBulitanSaleRepository>().Use<AdmissionBulitanSaleRepository>();
            For<IAdmissionEligibilityCriteriaRepository>().Use<AdmissionEligibilityCriteriaRepository>();
            For<IAdmissionSaleTypeRepository>().Use<AdmissionSaleTypeRepository>();
            For<IAdmissionStudentsRepository>().Use<AdmissionStudentsRepository>();
            For<IAdmissionStudentsImageRepository>().Use<AdmissionStudentsImageRepository>();
            For<IAttendanceAttendanceDetailRepository>().Use<AttendanceAttendanceDetailRepository>();
            For<IAttendanceAttendenceMasterRepository>().Use<AttendanceAttendenceMasterRepository>();
            For<IAttendanceAttendenceStatusRepository>().Use<AttendanceAttendenceStatusRepository>();
            For<IExaminationCampusGradingPolicyLinkRepository>().Use<ExaminationCampusGradingPolicyLinkRepository>();
            For<IExaminationExamDetailRepository>().Use<ExaminationExamDetailRepository>();
            For<IExaminationExamMasterRepository>().Use<ExaminationExamMasterRepository>();
            For<IExaminationExamMasterRepositoryVM>().Use<ExaminationExamMasterRepositoryVM>();
            For<IExaminationExamTypeRepository>().Use<ExaminationExamTypeRepository>();
            For<IExaminationGradingPolicyRepository>().Use<ExaminationGradingPolicyRepository>();
            For<IFeeBankRepository>().Use<FeeBankRepository>();
            For<IFeeCampusBankLinkRepository>().Use<FeeCampusBankLinkRepository>();
            For<IFeeCampusChallanNoteLinkRepository>().Use<FeeCampusChallanNoteLinkRepository>();
            For<IFeeChallanNoteRepository>().Use<FeeChallanNoteRepository>();
            For<IFeeChallanTypeRepository>().Use<FeeChallanTypeRepository>();
            For<IFeeChallanValidityRepository>().Use<FeeChallanValidityRepository>();
            For<IFeeConcessionRepository>().Use<FeeConcessionRepository>();
            For<IFeeConcessionDetailRepository>().Use<FeeConcessionDetailRepository>();
            For<IFeeConcessionDetailRepositoryVM>().Use<FeeConcessionDetailRepositoryVM>();
            For<IFeeContinuationPolicyRepository>().Use<FeeContinuationPolicyRepository>();
            For<IFeeFeeActivityRepository>().Use<FeeFeeActivityRepository>();
            For<IFeeFeeHeadRepository>().Use<FeeFeeHeadRepository>();
            For<IFeeFeeStructureRepository>().Use<FeeFeeStructureRepository>();
            For<IFeeFeeStructureDetailRepository>().Use<FeeFeeStructureDetailRepository>();
            For<IFeeFeeStructureDetailRepositoryVM>().Use<FeeFeeStructureDetailRepositoryVM>();
            For<IFeeScholarshipCriteriaRepository>().Use<FeeScholarshipCriteriaRepository>();
            // For<IFeeStudentChallanRepository>().Use<FeeStudentChallanRepository>();
            For<IFeeStudentFeeStructureRepository>().Use<FeeStudentFeeStructureRepository>();
            For<IHumanResourceDesignationsRepository>().Use<HumanResourceDesignationsRepository>();
            For<IHumanResourceStaffRepository>().Use<HumanResourceStaffRepository>();
            For<IStaffCourseRepository>().Use<StaffCourseRepository>();

            For<IRegistrationCourseRepository>().Use<RegistrationCourseRepository>();
            For<IRegistrationEnrollmentsRepository>().Use<RegistrationEnrollmentsRepository>();
            For<IRegistrationProgramCourseLinkRepository>().Use<RegistrationProgramCourseLinkRepository>();
            For<IRegistrationSectionCourseLinkRepository>().Use<RegistrationSectionCourseLinkRepository>();
             For<IAcademicSectionMapRepository>().Use<AcademicSectionMapRepository>();
            For<IRegistrationSectionsRepository>().Use<RegistrationSectionsRepository>();
            For<ISetupAddressRepository>().Use<SetupAddressRepository>();
            For<ISetupAdmissionTypeRepository>().Use<SetupAdmissionTypeRepository>();
            For<ISetupBloodGroupRepository>().Use<SetupBloodGroupRepository>();
            For<ISetupBoardRepository>().Use<SetupBoardRepository>();
            For<ISetupBoardTypeRepository>().Use<SetupBoardTypeRepository>();
            For<ISetupBuildingRepository>().Use<SetupBuildingRepository>();
            For<ISetupBuildingAddressLinkRepository>().Use<SetupBuildingAddressLinkRepository>();
            For<ISetupBusinessGroupRepository>().Use<SetupBusinessGroupRepository>();
            For<ISetupBusinessUnitRepository>().Use<SetupBusinessUnitRepository>();
            For<ISetupCampusRepository>().Use<SetupCampusRepository>();
            For<ISetupCampusBuildingLinkRepository>().Use<SetupCampusBuildingLinkRepository>();
            For<ISetupCampusBuildingLinkVMRepository>().Use<SetupCampusBuildingLinkVMRepository>();
            For<ISetupCampusProgramLinkRepository>().Use<SetupCampusProgramLinkRepository>();
            For<ISetupCityRepository>().Use<SetupCityRepository>();
            For<ISetupClassRepository>().Use<SetupClassRepository>();
            For<ISetupCollectorRepository>().Use<SetupCollectorRepository>();
            For<ISetupCountryRepository>().Use<SetupCountryRepository>();
            For<ISetupGenderRepository>().Use<SetupGenderRepository>();
            For<ISetupInstitutionRepository>().Use<SetupInstitutionRepository>();
            For<ISetupInstitutionTypeRepository>().Use<SetupInstitutionTypeRepository>();
            For<ISetupMediumRepository>().Use<SetupMediumRepository>();
            For<ISetupNationalityRepository>().Use<SetupNationalityRepository>();
            For<ISetupPossessionRepository>().Use<SetupPossessionRepository>();
            For<ISetupPossessionTypeRepository>().Use<SetupPossessionTypeRepository>();
            For<ISetupProgramRepository>().Use<SetupProgramRepository>();
            For<ISetupProgramDetailsRepository>().Use<SetupProgramDetailsRepository>();
            For<ISetupProvinceRepository>().Use<SetupProvinceRepository>();
            For<ISetupReligionRepository>().Use<SetupReligionRepository>();
            For<ISetupRoomRepository>().Use<SetupRoomRepository>();
            For<ISetupRoomBuildingLinkRepository>().Use<SetupRoomBuildingLinkRepository>();
            For<ISetupRoomTypeRepository>().Use<SetupRoomTypeRepository>();
            For<ISetupSectionRepository>().Use<SetupSectionRepository>();
            For<ISetupSessionRepository>().Use<SetupSessionRepository>();
            For<ISetupShiftRepository>().Use<SetupShiftRepository>();
            For<ISetupStatusRepository>().Use<SetupStatusRepository>();
            For<ISetupTermRepository>().Use<SetupTermRepository>();
            For<ISetupZoneRepository>().Use<SetupZoneRepository>();
            For<ISetupZoneCityLinkRepository>().Use<SetupZoneCityLinkRepository>();
            For<ITimeTableSlotsRepository>().Use<TimeTableSlotsRepository>();
            For<ITimeTableSlotTimingsRepository>().Use<TimeTableSlotTimingsRepository>();
            // For<ITimeTableTimeTableRepository>().Use<TimeTableTimeTableRepository>();
            For<ITimeTableTimeTableRepositoryVM>().Use<TimeTableTimeTableRepositoryVM>();
            For<ISetupProvinceVMRepository>().Use<SetupProvinceVMRepository>();
            For<ISetupBuildingAddressPossessionVMRepository>().Use<SetupBuildingAddressPossessionVMRepository>();
            For<ISetupRoomVMRepository>().Use<SetupRoomVMRepository>();
            For<ISetupInstitutionVMRepository>().Use<SetupInstitutionVMRepository>();
            For<IFeeCampusBankLinkVMRepository>().Use<FeeCampusBankLinkVMRepository>();
            For<IFeeChallanValidityVMRepository>().Use<FeeChallanValidityVMRepository>();
            For<IFeeConcessionVMRepository>().Use<FeeConcessionVMRepository>();
            For<IAdmissionEligibilityCriteriaVMRepository>().Use<AdmissionEligibilityCriteriaVMRepository>();
            For<IFeeCampusChallanNoteLinkVMRepository>().Use<FeeCampusChallanNoteLinkVMRepository>();
            For<ITimeTableSlotTimingsVMRepository>().Use<TimeTableSlotTimingsVMRepository>();
            For<IRegistrationProgramCourseLinkVMRepository>().Use<RegistrationProgramCourseLinkVMRepository>();
            For<IAdmissionStudentsImageVMRepository>().Use<AdmissionStudentsImageVMRepository>();
            For<IExaminationExamDetailRepository>().Use<ExaminationExamDetailRepository>();
            For<IExaminationExamDetailVMRepository>().Use<ExaminationExamDetailVMRepository>();
            For<IAttendanceAttendenceMasterVMRepository>().Use<AttendanceAttendenceMasterVMRepository>();
            For<IAttendanceAttendanceDetailVMRepository>().Use<AttendanceAttendanceDetailVMRepository>();
            //For<IAttendanceAttendanceReportRepository> ().Use<AttendanceAttendanceReportRepository> ();
            For<IELChaptersRepository>().Use<ELChaptersRepository>();
            For<IUserMcqResponseRepository>().Use<UserMcqResponseRepository>();
            For<IMcqAttemptedRepository>().Use<McqAttemptedRepository>();
            For<IChapterLinksRepository>().Use<ChapterLinksRepository>();

            For<IBoardProgramClassCourseLinkRepository>().Use<BoardProgramClassCourseLinkRepository>();

            For<IMCQsQuestionRepository>().Use<MCQsQuestionRepository>();
            For<IMCQsAnswersRepository>().Use<MCQsAnswersRepository>();
            For<IBoardsRepository>().Use<BoardsRepository>();
            For<ITopicVideoChapterLinkRepository>().Use<TopicVideoChapterLinkRepository>();
            For<IVideosRepository>().Use<VideosRepository>();
            For<IAcademicCalendarMasterRepository>().Use<AcademicCalendarMasterRepository>();

            For<ISetupExtraCourseRepository>().Use<SetupExtraCourseRepository>();


            For<IELModelPapersRepository>().Use<ELModelPapersRepository>();
            For<IELModelPapersQuestionsRepository>().Use<ELModelPapersQuestionsRepository>();
            For<IELQuestionsRepository>().Use<ELQuestionsRepository>();
            For<IELTopicsRepository>().Use<ELTopicsRepository>();
            For<ITopicWatchRepository>().Use<TopicWatchRepository>();

            For<IELTopicsRepositoryVM>().Use<ELTopicsRepositoryVM>();
            For<IELTopicLinkRepository>().Use<ELTopicLinkRepository>();

            For<ITeacherTimeTableReportRepository>().Use<TeacherTimeTableReportRepository>();
            For<IBoardProgramCampusRepository>().Use<BoardProgramCampusRepository>();
            For<IFeeStudentChallanVMRepository>().Use<FeeStudentChallanVMRepository>();
            For<IStudentRecordVMRepository>().Use<StudentRecordVMRepository>();
            For<IFeeStudentFeeStructureVMRepository>().Use<FeeStudentFeeStructureVMRepository>();
            For<ITableGradesRepository>().Use<TableGradesRepository>();
            For<IAdmissionReportsRepository>().Use<AdmissionReportsRepository>();
            For<ITimeTableReportsRepository>().Use<TimeTableReportsRepository>();
            For<IAdmissionReportsEnrolledRepository>().Use<AdmissionReportsEnrolledRepository>();
            For<IFeeReportsRepository>().Use<FeeReportsRepository>();
            For<ISetupSubCityRepository>().Use<SetupSubCityRepository>();

            For<ISetupOwnedCitySubCityRepository>().Use<SetupOwnedSubCityRepository>();

            For<ISetupCitySubCityLinkRepository>().Use<SetupCitySubCityLinkRepository>();
            For<ITransportationBusStopInfoRepository>().Use<TransportationBusStopInfoRepository>();
            For<ITransportationRouteDetailInfoRepository>().Use<TransportationRouteDetailInfoRepository>();
            For<ITransportationRouteInfoRepository>().Use<TransportationRouteInfoRepository>();
            For<ITransportationRouteStopLinkRepository>().Use<TransportationRouteStopLinkRepository>();
            For<ITransportationRouteStudentLinkRepository>().Use<TransportationRouteStudentLinkRepository>();
            For<ITransportationVehicleInfoRepository>().Use<TransportationVehicleInfoRepository>();
            For<IVWRouteDetailRepository>().Use<VWRouteDetailRepository>();
            For<IroutestudentlinkVMRepository>().Use<routestudentlinkVMRepository>();
            For<IroutestudentlinklistVMRepository>().Use<routestudentlinklistVMRepository>();
            //For<IAppExceptionRepository> ().Use<AppExceptionRepository> ();
            For<IVMTransportationRouteStopLinkRepository>().Use<VMTransportationRouteStopLinkRepository>();
            //For<IUserroleRepository>().Use<UserRolesRepository>();
            //Message
            For<ISmsRepository>().Use<SmsRepository>();
            For<IVWCustomDataRepository>().Use<VWCustomDataRepository>();
            For<ISmsAPIRepository>().Use<SmsAPIRepository>();
            For<ITemplatesRepository>().Use<TemplatesRepository>();
            // Seating Plan
            For<ISeatingPlanDateSheetRepository>().Use<SeatingPlanDateSheetRepository>();
            For<ISeatingPlanDateSheetDetailRepository>().Use<SeatingPlanDateSheetDetailRepository>();

            // Extended Repository
            For<IFeeStudentChallanRepositoryEx>().Use<FeeStudentChallanRepositoryEx>();

            For<IHolidayTypeRepository>().Use<HolidayTypeRepository>();


            For<IHolidayRepository>().Use<HolidayRepository>();
            For<IOnlineAdmissionRepository>().Use<OnlineAdmissionRepository>();
            For<IAssessmentSchedulingRepository>().Use<AssessmentSchedulingRepository>();
            For<IAssessmentScheduleMasterRepository>().Use<AssessmentScheduleMasterRepository>();
            For<IARVO_ConfigurationsRepository>().Use<ARVO_ConfigurationsRepository>();
            For<IQuizResultRepository>().Use<QuizResultRepository>();
            For<IARVOConfigurationRepository>().Use<ARVOConfigurationRepository>();

            


        }
    }
}