import { IUser } from "../../../model";

export interface IMenuModel {
  badge: string;
  header: string;
  iconName: string;
  headerLink: string;
  link: string;
  childrenLinks: Array<IMenuModel>;
  className: string;
  isHeader: boolean;
  deep: number;
  activeItem: string;
  label: string;
  index: string;
  isVisable: boolean;
  name: string;
}

const menu: Array<IMenuModel> = [
  {
    name: "bsetup",
    iconName: "airplay",
    link: "/",
    header: "Setup",
    childrenLinks: [
      {
        name: "rsetup",
        iconName: "icon-layers",
        link: "/",
        header: "Annual",
        childrenLinks: [
          {
            name: "setupSession",
            iconName: "icon-layers",
            link: "/setupSession",
            header: "Session",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupCampusProgramLink",
            iconName: "icon-layers",
            link: "/setupCampusProgramLink",
            header: "Campus Program Link",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "admissionEligibilityCriteria",
            iconName: "icon-layers",
            link: "/admissionEligibilityCriteria",
            header: "Eligibility Criteria",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "registrationProgramCourseLink",
            iconName: "icon-layers",
            link: "/registrationProgramCourseLink",
            header: "Program Course Link",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
        ],
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "gsetup",
        iconName: "icon-layers",
        link: "/",
        header: "General",
        childrenLinks: [
          {
            name: "setupBusinessGroup",
            iconName: "icon-layers",
            link: "/setupBusinessGroup",
            header: "Business Group",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupBusinessUnit",
            iconName: "icon-layers",
            link: "/setupBusinessUnit",
            header: "Business Unit",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupInstitution",
            iconName: "icon-layers",
            link: "/setupInstitution",
            header: "Institution",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupCampus",
            iconName: "icon-layers",
            link: "/setupCampus",
            header: "Campus",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupZone",
            iconName: "icon-layers",
            link: "/setupZone",
            header: "Zone",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupClass",
            iconName: "icon-layers",
            link: "/setupClass",
            header: "Class",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupSubCity",
            iconName: "icon-layers",
            link: "/setupSubCity",
            header: "Sub City",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupProgram",
            iconName: "icon-layers",
            link: "/setupProgram",
            header: "Program",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupProgramDetails",
            iconName: "icon-layers",
            link: "/setupProgramDetails",
            header: "Program Details",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupCountry",
            iconName: "icon-layers",
            link: "/setupCountry",
            header: "Country",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupProvince",
            iconName: "icon-layers",
            link: "/setupProvince",
            header: "Province",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupCity",
            iconName: "icon-layers",
            link: "/setupCity",
            header: "City",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupAddress",
            iconName: "icon-layers",
            link: "/setupAddress",
            header: "Address",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupAdmissionType",
            iconName: "icon-layers",
            link: "/setupAdmissionType",
            header: "Admission Type",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupBloodGroup",
            iconName: "icon-layers",
            link: "/setupBloodGroup",
            header: "Blood Group",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupBoard",
            iconName: "icon-layers",
            link: "/setupBoard",
            header: "Board",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupBoardType",
            iconName: "icon-layers",
            link: "/setupBoardType",
            header: "Board Type",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "franchise",
            iconName: "icon-layers",
            link: "/franchise",
            header: "Franchise",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupGender",
            iconName: "icon-layers",
            link: "/setupGender",
            header: "Gender",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupInstitutionType",
            iconName: "icon-layers",
            link: "/setupInstitutionType",
            header: "Institution Type",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupMedium",
            iconName: "icon-layers",
            link: "/setupMedium",
            header: "Medium",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupMonth",
            iconName: "icon-layers",
            link: "/setupMonth",
            header: "Month",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupNationality",
            iconName: "icon-layers",
            link: "/setupNationality",
            header: "Nationality",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupPossession",
            iconName: "icon-layers",
            link: "/setupPossession",
            header: "Possession",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupPossessionType",
            iconName: "icon-layers",
            link: "/setupPossessionType",
            header: "Possession Type",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupReligion",
            iconName: "icon-layers",
            link: "/setupReligion",
            header: "Religion",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupPassStatus",
            iconName: "icon-layers",
            link: "/setupPassStatus",
            header: "Pass Status",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "admissionSaleType",
            iconName: "icon-layers",
            link: "/admissionSaleType",
            header: "Sale Types",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "timeTableSlots",
            iconName: "settings",
            link: "/timeTableSlots",
            header: "Slots",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "timeTableSlotTimings",
            iconName: "settings",
            link: "/timeTableSlotTimings",
            header: "Slot Timings",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "messageSMSAPIList",
            iconName: "icon-layers",
            link: "/messageSMSAPIList",
            header: "Messages API",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
        ],
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "blsetup",
        iconName: "icon-layers",
        link: "/",
        header: "Building",
        childrenLinks: [
          {
            name: "setupBuilding",
            iconName: "icon-layers",
            link: "/setupBuilding",
            header: "Building",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupCampusBuildingLink",
            iconName: "icon-layers",
            link: "/setupCampusBuildingLink",
            header: "Campus Building Link",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupRoom",
            iconName: "icon-layers",
            link: "/setupRoom",
            header: "Room",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupRoomBuildingLink",
            iconName: "icon-layers",
            link: "/setupRoomBuildingLink",
            header: "Room Building Link",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupRoomType",
            iconName: "icon-layers",
            link: "/setupRoomType",
            header: "Room Type",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "examinationExamSectionLink",
            iconName: "icon-layers",
            link: "/examinationExamSectionLink",
            header: "Building Section Link",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          // { isVisable: true, name: 'examinationExamSectionLink', icon: 'icon-layers', route: 'examinationExamSectionLink', caption: 'Building Section Link', children: [] },
        ],
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "csetup",
        iconName: "icon-layers",
        link: "/",
        header: "Academic",
        childrenLinks: [
          {
            name: "setupSection",
            iconName: "icon-layers",
            link: "/setupSection",
            header: "Section",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "registrationCourse",
            iconName: "icon-layers",
            link: "/registrationCourse",
            header: "Course",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupShift",
            iconName: "icon-layers",
            link: "/setupShift",
            header: "Shift",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupTerm",
            iconName: "icon-layers",
            link: "/setupTerm",
            header: "Term",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupGroup",
            iconName: "icon-layers",
            link: "/setupGroup",
            header: "Group",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupDegree",
            iconName: "icon-layers",
            link: "/setupDegree",
            header: "Degree",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
        ],
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "fsetup",
        iconName: "icon-layers",
        link: "/",
        header: "Fee",
        childrenLinks: [
          {
            name: "feeFeeHead",
            iconName: "icon-layers",
            link: "/feeFeeHead",
            header: "Fee Head",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupConcessionRemarks",
            iconName: "icon-layers",
            link: "/setupConcessionRemarks",
            header: "Concession Remarks",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeFeeStructureSingle",
            iconName: "icon-layers",
            link: "/feeFeeStructureSingle",
            header: "Fee Structure",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeFeeStructure",
            iconName: "icon-layers",
            link: "/feeFeeStructure",
            header: "Fee Structure Bulk",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeContinuationPolicy",
            iconName: "icon-layers",
            link: "/feeContinuationPolicy",
            header: "Continuation Policy",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeTBLGrades",
            iconName: "icon-layers",
            link: "/feeTBLGrades",
            header: "Grades",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeConcessionBulk",
            iconName: "icon-layers",
            link: "/feeConcessionBulk",
            header: "Concession Bulk",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeConcession",
            iconName: "icon-layers",
            link: "/feeConcession",
            header: "Concession",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeConcessionDetail",
            iconName: "icon-layers",
            link: "/feeConcessionDetail",
            header: "Concession Detail",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeFeeStructureApproval",
            iconName: "icon-layers",
            link: "/feeFeeStructureApproval",
            header: "Fee Structure Approval",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "setupCollector",
            iconName: "icon-layers",
            link: "/setupCollector",
            header: "Collector",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeBank",
            iconName: "icon-layers",
            link: "/feeBank",
            header: "Bank",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeCampusBankLink",
            iconName: "icon-layers",
            link: "/feeCampusBankLink",
            header: "Campus Bank Link",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "adhocChallanLink",
            iconName: "icon-layers",
            link: "/adhocChallanLink",
            header: "Adhoc Challan",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeCampusChallanNoteLink",
            iconName: "icon-layers",
            link: "/feeCampusChallanNoteLink",
            header: "Campus Challan Note Link",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeChallanNote",
            iconName: "icon-layers",
            link: "/feeChallanNote",
            header: "Challan Note",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeChallanType",
            iconName: "icon-layers",
            link: "/feeChallanType",
            header: "Challan Type",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeChallanValidity",
            iconName: "icon-layers",
            link: "/feeChallanValidity",
            header: "Challan Validity",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeFeeStructureDetail",
            iconName: "icon-layers",
            link: "/feeFeeStructureDetail",
            header: "Fee Structure Detail",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
          {
            name: "feeScholarshipCriteria",
            iconName: "icon-layers",
            link: "/feeScholarshipCriteria",
            header: "Scholarship Criteria",
            badge: "",
            headerLink: "",
            className: "",
            activeItem: "",
            label: "",
            index: "",
            childrenLinks: null,
            isHeader: false,
            deep: 0,
            isVisable: true,
          },
        ],
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "board",
    iconName: "award",
    link: "/",
    header: "Board",
    childrenLinks: [
      {
        name: "boardCampus",
        iconName: "icon-layers",
        link: "/boardCampus",
        header: "Board Campus",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "boardCampusStudentLink",
        iconName: "icon-layers",
        link: "/boardCampusStudentLink",
        header: "Campus Student Link",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "admission",
    iconName: "award",
    link: "/",
    header: "Admission",
    childrenLinks: [
      {
        name: "admissionAdmissionForm",
        iconName: "icon-layers",
        link: "/admissionAdmissionForm",
        header: "Admission Form",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "admissionBulitanSale",
        iconName: "icon-layers",
        link: "/admissionBulitanSale",
        header: "Bulletin Sale",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "admissionStudents",
        iconName: "icon-layers",
        link: "/admissionStudents",
        header: "StudentsInfo",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "programTransfer",
        iconName: "icon-layers",
        link: "/programTransfer",
        header: "Program Transfer",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "StateChange",
        iconName: "icon-layers",
        link: "/StateChange",
        header: "State Change",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "admissionReports",
        iconName: "icon-layers",
        link: "/admissionReports",
        header: "Admission Reports",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "assessment",
    iconName: "award",
    link: "/",
    header: "Assessment",
    childrenLinks: [
      {
        name: "assessmentCategory",
        iconName: "icon-layers",
        link: "/assessmentCategory",
        header: "Assessment Category",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "assessmentSchedule",
        iconName: "icon-layers",
        link: "/assessmentSchedule",
        header: "Assessment Schedule",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "fee",
    iconName: "dollar-sign",
    link: "/",
    header: "Fee Management",
    childrenLinks: [
      {
        name: "feeStudentChallanPaidList",
        iconName: "icon-layers",
        link: "/feeStudentChallanPaidList",
        header: "Paid Date Removal",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "feeApplyConcessionBulk",
        iconName: "icon-layers",
        link: "/feeApplyConcessionBulk",
        header: "Apply Concession Bulk",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "feeApplyConcession",
        iconName: "icon-layers",
        link: "/feeApplyConcession",
        header: "Apply Concession",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "feeApplyScholarship",
        iconName: "icon-layers",
        link: "/feeApplyScholarship",
        header: "Apply Scholarship Bulk",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "feeSubInstallment",
        iconName: "icon-layers",
        link: "/feeSubInstallment",
        header: "Fee Installments",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "feeExemption",
        iconName: "icon-layers",
        link: "/fullfeeChallan",
        header: "Full Fee Challan",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "singleConcession",
        iconName: "icon-layers",
        link: "/singleConcession",
        header: "Single Concession",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "changeDueDate",
        iconName: "icon-layers",
        link: "/changeDueDate",
        header: "Change Due Date",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "feeConfirmation",
        iconName: "icon-layers",
        link: "/feeConfirmation",
        header: "Student Fee Confirmation",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      
        {
        name: "refundchallan",
        iconName: "icon-layers",
        link: "/refundchallan",
        header: "Refund Challan",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },  


      {
        name: "feeChallanSearch",
        iconName: "icon-layers",
        link: "/feeChallanSearch",
        header: "Search Fee Challan",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "changePaidDate",
        iconName: "icon-layers",
        link: "/changePaidDate",
        header: "Change Paid Date",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "concessionReports",
        iconName: "icon-layers",
        link: "/concessionReports",
        header: "Concession Reports",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "previousFee",
        iconName: "icon-layers",
        link: "/previousFee",
        header: "1st Year Fee",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "customChallan",
        iconName: "icon-layers",
        link: "/customChallan",
        header: "Custom Challan",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "feeReports",
        iconName: "icon-layers",
        link: "/feeReports",
        header: "Fee Reports",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },

      {
        name: "financeReports",
        iconName: "icon-layers",
        link: "/financeReports",
        header: "Fee Reports",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },

      {
        name: "concessionRenew",
        iconName: "icon-layers",
        link: "/concessionRenew",
        header: "Re-New Concession",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "timetable",
    iconName: "watch",
    link: "/",
    header: "Time Table",
    childrenLinks: [
      {
        name: "timeTableTimeTable",
        iconName: "settings",
        link: "/timeTableTimeTable",
        header: "Time Table",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "timeTableTimeTableMerge",
        iconName: "settings",
        link: "/timetableMerge",
        header: "Time Table Merge",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "attendance",
    iconName: "user-check",
    link: "/",
    header: "Attendance",
    childrenLinks: [
      {
        name: "attendanceAttendenceMaster",
        iconName: "settings",
        link: "/attendanceAttendenceMaster",
        header: "Attendence Master",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "attendanceAttendenceStatus",
        iconName: "settings",
        link: "/attendanceAttendenceStatus",
        header: "Attendence Status",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "attendanceBulk",
        iconName: "settings",
        link: "/attendanceBulk",
        header: "Attendance",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "attendanceTeacher",
        iconName: "settings",
        link: "/attendanceTeacher",
        header: "Attendance Teacher",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "attendanceTeacherUser",
        iconName: "settings",
        link: "/attendanceTeacherUser",
        header: "User Attendence",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "dayClose",
        iconName: "settings",
        link: "/dayClose",
        header: "Day Close",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "attendanceBulkDetail",
        iconName: "settings",
        link: "/attendanceBulkDetail",
        header: "Attendance Bulk",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "leaveManagement",
        iconName: "settings",
        link: "/leaveManagement",
        header: "Leave Management",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "attendanceApproval",
        iconName: "settings",
        link: "/attendanceApproval",
        header: "Attendance Approval",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "struckoffReinstate",
        iconName: "icon-layers",
        link: "/struckoffReinstate",
        header: "Struckoff Reinstate",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "attendanceHistory",
        iconName: "icon-layers",
        link: "/attendanceHistory",
        header: "Attendance History",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "attendanceReports",
        iconName: "settings",
        link: "/attendanceReports",
        header: "Attendance Report",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "registration",
    iconName: "user-plus",
    link: "/",
    header: "Registration",
    childrenLinks: [
      {
        name: "registrationSectionCourseLink",
        iconName: "icon-layers",
        link: "/registrationSectionCourseLink",
        header: "Section Campus Link",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "enrollmentBulk",
        iconName: "icon-layers",
        link: "/enrollmentBulk",
        header: "Enrollment Bulk",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "enrollmentReverse",
        iconName: "icon-layers",
        link: "/enrollmentReverse",
        header: "Enrollment Reverse",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "sectionChange",
        iconName: "icon-layers",
        link: "/sectionChange",
        header: "Section Change",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "enrolledReports",
        iconName: "icon-layers",
        link: "/enrolledReports",
        header: "Enrollment Reports",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "transportation",
    iconName: "truck",
    link: "/",
    header: "Transportation",
    childrenLinks: [
      {
        name: "routeInfo",
        iconName: "icon-layers",
        link: "/routeInfo",
        header: "Route",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "routeDetailInfo",
        iconName: "icon-layers",
        link: "/routeDetailInfo",
        header: "Route Detail",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "vehicleInfo",
        iconName: "icon-layers",
        link: "/vehicleInfo",
        header: "Vehicle Info",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "routeStudentLink",
        iconName: "icon-layers",
        link: "/routeStudentLink",
        header: "Route Student Link",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "busStopInfo",
        iconName: "icon-layers",
        link: "/busStopInfo",
        header: "Bus Stop Info",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "routeStopLink",
        iconName: "icon-layers",
        link: "/routeStopLink",
        header: "Route Stop Link",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "feeConfirmationEx",
        iconName: "icon-layers",
        link: "/feeConfirmationEx",
        header: "Other Challan Confirmation",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "examination",
    iconName: "clipboard",
    link: "/",
    header: "Examination",
    childrenLinks: [
      {
        name: "examinationExamType",
        iconName: "icon-layers",
        link: "/examinationExamType",
        header: "Exam Type",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "examBulk",
        iconName: "icon-layers",
        link: "/examBulk",
        header: "Examination Bulk",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "examinationExamSchedule",
        iconName: "icon-layers",
        link: "/examinationExamSchedule",
        header: "Exam Schedule",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "examApproval",
        iconName: "icon-layers",
        link: "/examApproval",
        header: "Exam Approval",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "examSMSApproval",
        iconName: "icon-layers",
        link: "/examSMSApproval",
        header: "Exam SMS Approval",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "gradingPolicyBulk",
        iconName: "icon-layers",
        link: "/gradingPolicyBulk",
        header: "Grading Policy Bulk",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "examinationExamSectionLink",
        iconName: "icon-layers",
        link: "/examinationExamSectionLink",
        header: "Building Section Link",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "campusFailCriteriaMapping",
        iconName: "icon-layers",
        link: "/campusFailCriteriaMapping",
        header: "Campus Fail Criteria",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "campusGradingMapping",
        iconName: "icon-layers",
        link: "/campusGradingMapping",
        header: "Campus Grading",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "examinationReports",
        iconName: "icon-layers",
        link: "/examinationReports",
        header: "Examination Reports",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "failCriteria",
        iconName: "icon-layers",
        link: "/failCriteria",
        header: "Fail Criteria",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "Message",
    iconName: "clipboard",
    link: "/",
    header: "Message",
    childrenLinks: [
      {
        name: "customSms",
        iconName: "icon-layers",
        link: "/customSms",
        header: "Custom Messages",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "messageTemplate",
        iconName: "icon-layers",
        link: "/messageTemplate",
        header: "Messages Template",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "el",
    iconName: "monitor",
    link: "/",
    header: "EL",
    childrenLinks: [
      {
        name: "elChapters",
        iconName: "icon-layers",
        link: "/elChapters",
        header: "Chapters",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "elModelPapers",
        iconName: "icon-layers",
        link: "/elModelPapers",
        header: "Model Papers",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "elModelPapersQuestions",
        iconName: "icon-layers",
        link: "/elModelPapersQuestions",
        header: "Model Question Paper",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "elQuestions",
        iconName: "icon-layers",
        link: "/elQuestions",
        header: "Questions",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "elTopics",
        iconName: "icon-layers",
        link: "/elTopics",
        header: "Topics",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "hr",
    iconName: "users",
    link: "/",
    header: "HR",
    childrenLinks: [
      {
        name: "humanResourceDepartments",
        iconName: "icon-layers",
        link: "/humanResourceDepartments",
        header: "Departments",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "humanResourceDesignations",
        iconName: "icon-layers",
        link: "/humanResourceDesignations",
        header: "Designations",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "humanResourceStaff",
        iconName: "icon-layers",
        link: "/humanResourceStaff",
        header: "Staff",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "role",
    iconName: "slack",
    link: "/",
    header: "Roles",
    childrenLinks: [
      {
        name: "RolePrevilages",
        iconName: "icon-layers",
        link: "/roleprevilages",
        header: "Privileges",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "UserLog",
        iconName: "icon-layers",
        link: "/userLog",
        header: "UserLog",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "SecurityClaims",
        iconName: "icon-layers",
        link: "/securityclaims",
        header: "SecurityClaims",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "SectionRightLink",
        iconName: "icon-layers",
        link: "/sectionRightLink",
        header: "Section Rights",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
  {
    name: "migrate",
    iconName: "clipboard",
    link: "/",
    header: "Migrate",
    childrenLinks: [
      {
        name: "enrollmentBulkWithoutPaid",
        iconName: "icon-layers",
        link: "/enrollmentBulkWithoutPaid",
        header: "Hadaf Migration",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "enrollmentBulkWithoutPaidEx",
        iconName: "icon-layers",
        link: "/enrollmentBulkWithoutPaidEx",
        header: "Cms Migration",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "admissionAdmissionFormDirectEnroll",
        iconName: "icon-layers",
        link: "/admissionAdmissionFormDirectEnroll",
        header: "Admission Enrollment",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
      {
        name: "classTransfer",
        iconName: "icon-layers",
        link: "/classTransfer",
        header: "Class Transfer",
        badge: "",
        headerLink: "",
        className: "",
        activeItem: "",
        label: "",
        index: "",
        childrenLinks: null,
        isHeader: false,
        deep: 0,
        isVisable: true,
      },
    ],
    badge: "",
    headerLink: "",
    className: "",
    activeItem: "",
    label: "",
    index: "",
    isHeader: false,
    deep: 0,
    isVisable: true,
  },
];

export class GenerateMenu {
  private user: IUser;

  constructor(tempUser: IUser) {
    this.user = tempUser;
  }

  processMenu(): Array<IMenuModel> {
    var tempMenu = menu;

    tempMenu.forEach((item) => {
      if (!item.childrenLinks) {
        item.childrenLinks.forEach((element) => {
          this.processMenuEx(element);
        });

        item.isVisable = this.hasChildrenVisible(item);
      } else {
        item.isVisable = this.foundInRoule(item.link);
      }
    });

    return tempMenu;
  }

  private processMenuEx(item: IMenuModel) {
    if (!item.childrenLinks) {
      item.childrenLinks.forEach((element) => {
        this.processMenuEx(element);
      });

      item.isVisable = this.hasChildrenVisible(item);
    } else {
      item.isVisable = this.foundInRoule(item.link);
    }
  }

  private foundInRoule(value) {
    var found: boolean = false;
    if (this.user.claims[value] != undefined) {
      found = true;
    }
    return found;
  }

  private hasChildrenVisible(item: IMenuModel) {
    var found: boolean = false;
    item.childrenLinks.forEach((element) => {
      if (element.isVisable === true) {
        found = true;
      }
    });
    return found;
  }
}
