import * as icons from "./svgPath";

import { IUser, SecurityRoleClaims } from "../../../model";

import { AuthenticationService } from "../../../services";
import { Store } from "../../store/store";
import { settings } from "cluster";

export interface IMenu {
  name: string;
  route: string;
  svgPath: string;
  isVisable: boolean;
  isHeader: boolean;
  children: Array<IMenu>;
}

const providedMenu: Array<IMenu> = [
  {
    isVisable: true,
    name: "dashboard",
    svgPath: icons.dashboard,
    isHeader: true,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "quizDashboard",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "quizDashboard",
      },
      {
        isVisable: true,
        name: "attendanceAttendenceDashboard",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "attendanceAttendenceDashboard",
      },
      {
        isVisable: true,
        name: "concessionDashboard",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "concessionDashboard",
      },
      {
        isVisable: true,
        name: "revenueDashboard",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "revenueDashboard",
      },
      {
        isVisable: true,
        name: "feePaidDashboard",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feePaidDashboard",
      },
      {
        isVisable: true,
        name: "attendanceAttendenceDashboard2",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "attendanceAttendenceDashboard2",
      },
      {
        isVisable: true,
        name: "studentfeedback",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "studentfeedback",
      },
      {
        isVisable: true,
        name: "notificationDashboard",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "surveyDashboard",
      },
      // { isVisable: true, name: 'CMSStudentCount', svgPath: 'icon-layers', children: null, isHeader: false, route: 'CMSStudentCount' },
      // { isVisable: true, name: 'survey', svgPath: 'icon-layers', children: null, isHeader: false, route: 'dashboardSurveyMaster' },
      // { isVisable: true, name: 'surveydetail', svgPath: 'icon-layers', children: null, isHeader: false, route: 'dashboardSurveyDetail' },

      // {
      //   isVisable: true,
      //   name: "CMSStudentCountEbook2024Statistics",
      //   svgPath: "icon-layers",
      //   children: null,
      //   isHeader: false,
      //   route: "CMSStudentCountEbook2024Statistics",
      // },
      {
        isVisable: true,
        name: "CMSStudentCountEbook2024",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "CMSStudentCountEbook2024",
      },

      {
        isVisable: true,
        name: "rstdservay",
        svgPath: icons.admission,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "CMSStudentCountJan2026Statistics",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountJan2026Statistics",
          },
           {
            isVisable: true,
            name: "SurveyDashboardJanuary26",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "SurveyDashboardJanuary26",
          },
          {
            isVisable: true,
            name: "CMSStudentCountJan2025Statistics",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountJan2025Statistics",
          },

          {
            isVisable: true,
            name: "SurveyDashboardJanuary25",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "SurveyDashboardJanuary25",
          },
          {
            isVisable: true,
            name: "SurveyDashboardJanuary24",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "SurveyDashboardJanuary24",
          },
          {
            isVisable: true,
            name: "CMSStudentCountJuly2023Statistics",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountJuly2023Statistics",
          },

          {
            isVisable: true,
            name: "CMSStudentCountJune2024Statistics",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountJune2024Statistics",
          },


          {
            isVisable: true,
            name: "CMSStudentCountDecember2022",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountDecember2022",
          },
          {
            isVisable: true,
            name: "CMSStudentCountjuly2023",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountjuly2023",
          },

          {
            isVisable: true,
            name: "CMSStudentCountjune2024",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountjune2024",
          },
          {
            isVisable: true,
            name: "CMSStudentCountJan2022",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountjan2022",
          },
          {
            isVisable: true,
            name: "CMSStudentCountDecember2021",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountDecember2021",
          },
          {
            isVisable: true,
            name: "CMSStudentCountApril2022",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "CMSStudentCountApril2022",
          },

        ],
      },

      // { isVisable: true, name: 'notificationDash', svgPath: 'icon-layers', children: null, isHeader: false, route: 'notificationDashboard2' },
      {
        isVisable: true,
        name: "rsetup",
        svgPath: icons.admission,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "admissionDashboard",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionDashboard",
          },
          {
            isVisable: true,
            name: "datePeriodComparison",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionComaprisonDashboard",
          },
          {
            isVisable: true,
            name: "datePeriodComparisonCampusWise",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionComaprisonDashboardCampusWise",
          },
          {
            isVisable: true,
            name: "admissionComaprisonDashboardCampusWiseClone",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionComaprisonDashboardCampusWiseClone",
          },
          {
            isVisable: true,
            name: "yearoverYearComparison",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "comparisonDashboard",
          },
        ],
      },
    ],
  },


  // {
  //     isVisable: true,
  //     name: "assessment",
  //     svgPath: icons.personalinfo,
  //     isHeader: false,
  //     route: "#",
  //     children: [

  //             {
  //                 isVisable: true,
  //                 name: "assessmentCategory",
  //                 svgPath: "icon-layers",
  //                 children: null,
  //                 isHeader: false,
  //                 route: "assessmentCategory",
  //             },

  //             {
  //                 isVisable: true,
  //                 name: "assessmentSchedule",
  //                 svgPath: "icon-layers",
  //                 children: null,
  //                 isHeader: false,
  //                 route: "assessmentSchedule",
  //             },

  //     ]
  // },

  {
    isVisable: true,
    name: "ssetup",
    svgPath: icons.systemSetting,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "rsetup",
        svgPath: icons.admission,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "setupSession",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupSession",
          },
          {
            isVisable: true,
            name: "setupCampusProgramLink",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupCampusProgramLink",
          },
          {
            isVisable: true,
            name: "registrationProgramCourseLink",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "registrationProgramCourseLink",
          },
          // { isVisable: true, name: 'setupBloodGroup', svgPath: 'icon-layers', children: null, isHeader: false, route: 'setupBloodGroup' },
          {
            isVisable: true,
            name: "setupBoard",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupBoard",
          },
          {
            isVisable: true,
            name: "setupBoardType",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupBoardType",
          },
          {
            isVisable: true,
            name: "setupGender",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupGender",
          },
          {
            isVisable: true,
            name: "setupMedium",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupMedium",
          },
          {
            isVisable: true,
            name: "setupMonth",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupMonth",
          },
          {
            isVisable: true,
            name: "setupNationality",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupNationality",
          },
          {
            isVisable: true,
            name: "setupReligion",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupReligion",
          },
          {
            isVisable: true,
            name: "setupAdmissionType",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupAdmissionType",
          },
          {
            isVisable: true,
            name: "setupDegree",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupDegree",
          },
          {
            isVisable: true,
            name: "setupGroup",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupGroup",
          },
          {
            isVisable: true,
            name: "attendanceAttendenceStatus",
            svgPath: "settings",
            children: null,
            isHeader: false,
            route: "attendanceAttendenceStatus",
          },
        ],
      },
      {
        isVisable: true,
        name: "gsetup",
        svgPath: icons.folder,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "setupBusinessGroup",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupBusinessGroup",
          },
          {
            isVisable: true,
            name: "setupBusinessUnit",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupBusinessUnit",
          },

          {
            isVisable: true,
            name: "setupInstitution",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupInstitution",
          },
          {
            isVisable: true,
            name: "setupCampus",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupCampus",
          },
          {
            isVisable: true,
            name: "setupZone",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupZone",
          },
          {
            isVisable: true,
            name: "setupCountry",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupCountry",
          },
          {
            isVisable: true,
            name: "setupProvince",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupProvince",
          },
          {
            isVisable: true,
            name: "setupCity",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupCity",
          },
          {
            isVisable: true,
            name: "setupSubCity",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupSubCity",
          },
          {
            isVisable: true,
            name: "setupClass",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupClass",
          },
          {
            isVisable: true,
            name: "franchise",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "franchise",
          },
          {
            isVisable: true,
            name: "setupInstitutionType",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupInstitutionType",
          },
          {
            isVisable: true,
            name: "messageSMSAPIList",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "messageSMSAPIList",
          },
          {
            isVisable: true,
            name: "setupShift",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupShift",
          },
          {
            isVisable: true,
            name: "gradingPolicyBulk",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "gradingPolicyBulk",
          },
          {
            isVisable: true,
            name: "failCriteria",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "failCriteria",
          },

          {
            isVisable: true,
            name: "messageTemplate",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "messageTemplate",
          },
        ],
      },
      {
        isVisable: true,
        name: "blsetup",
        svgPath: icons.building,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "setupBuilding",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupBuilding",
          },
          {
            isVisable: true,
            name: "setupCampusBuildingLink",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupCampusBuildingLink",
          },
          {
            isVisable: true,
            name: "setupRoom",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupRoom",
          },
          // { isVisable: true, name: 'setupRoomBuildingLink', svgPath: 'icon-layers', children: null, isHeader: false, route: 'setupRoomBuildingLink' },
          {
            isVisable: true,
            name: "setupRoomType",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupRoomType",
          },
          {
            isVisable: true,
            name: "examinationExamSectionLink",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "examinationExamSectionLink",
          },
          {
            isVisable: true,
            name: "setupPossession",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupPossession",
          },
          {
            isVisable: true,
            name: "setupPossessionType",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupPossessionType",
          },
          {
            isVisable: true,
            name: "setupAddress",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupAddress",
          },
        ],
      },
      {
        isVisable: true,
        name: "Survey",
        svgPath: icons.building,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "survey",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "dashboardSurveyMaster",
          },
          {
            isVisable: true,
            name: "surveydetail",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "dashboardSurveyDetail",
          },
        ],
      },

      {
        isVisable: true,
        name: "csetup",
        svgPath: icons.book,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "setupProgram",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupProgram",
          },
          {
            isVisable: true,
            name: "setupProgramDetails",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupProgramDetails",
          },
          {
            isVisable: true,
            name: "setupSection",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "setupSection",
          },
          {
            isVisable: true,
            name: "registrationCourse",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "registrationCourse",
          },
          {
            isVisable: true,
            name: "timeTableSlots",
            svgPath: "settings",
            children: null,
            isHeader: false,
            route: "timeTableSlots",
          },
          {
            isVisable: true,
            name: "timeTableSlotTimings",
            svgPath: "settings",
            children: null,
            isHeader: false,
            route: "timeTableSlotTimings",
          },
        ],
      },
      {
        isVisable: true,
        name: "fsetup",
        svgPath: icons.money,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "feeFeeHead",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeFeeHead",
          },

          {
            isVisable: true,
            name: "feeFeeStructure",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeFeeStructure",
          },
          {
            isVisable: true,
            name: "feeContinuationPolicy",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeContinuationPolicy",
          },

          {
            isVisable: true,
            name: "feeConcessionBulk",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeConcessionBulk",
          },
          {
            isVisable: true,
            name: "feeConcession",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeConcession",
          },
          {
            isVisable: true,
            name: "feeConcessionDetail",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeConcessionDetail",
          },
          {
            isVisable: true,
            name: "feeFeeStructureApproval",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeFeeStructureApproval",
          },
          {
            isVisable: true,
            name: "minimumPaidDate",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "minimumPaidDate",
          },
          {
            isVisable: true,
            name: "feeBank",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeBank",
          },
          {
            isVisable: true,
            name: "feeCampusChallanNoteLink",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeCampusChallanNoteLink",
          },
          {
            isVisable: true,
            name: "feeChallanNote",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeChallanNote",
          },
          {
            isVisable: true,
            name: "feeChallanType",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeChallanType",
          },
          {
            isVisable: true,
            name: "feeFeeStructureDetail",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeFeeStructureDetail",
          },
          {
            isVisable: true,
            name: "feeScholarshipCriteria",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "feeScholarshipCriteria",
          },
        ],
      },
      {
        isVisable: true,
        name: "migrate",
        svgPath: icons.migrate,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "enrollmentBulkWithoutPaid",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "enrollmentBulkWithoutPaid",
          },
          {
            isVisable: true,
            name: "enrollmentBulkWithoutPaidEx",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "enrollmentBulkWithoutPaidEx",
          },
          {
            isVisable: true,
            name: "admissionAdmissionFormDirectEnroll",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionAdmissionFormDirectEnroll",
          },
          // { isVisable: true, name: 'classTransfer', svgPath: 'icon-layers', children: null, isHeader: false, route: 'classTransfer' },
          {
            isVisable: true,
            name: "elMigration",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "elMigration",
          },
          {
            isVisable: true,
            name: "elUpdation",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "elUpdation",
          },

          {
            isVisable: true,
            name: "attendancePercentage",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "attendancePercentage",
          },
          //{ isVisable: true, name: 'admissionDuplicateRemove', svgPath: 'icon-layers', children: null, isHeader: false, route: 'admissionDuplicateRemove' },
        ],
      },
    ],
  },
  {
    isVisable: true,
    name: "bsetup",
    svgPath: icons.systemSetting,
    isHeader: false,
    route: "#",
    children: [
      //  {
      //       isVisable: true,
      //       name: "bulkCopyProgramDetailName",
      //       svgPath: "icon-layers",
      //       children: null,
      //       isHeader: false,
      //       route: "bulkCopyProgramDetail",
      //     },
      {
        isVisable: true,
        name: "admissionEligibilityCriteria",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "admissionEligibilityCriteria",
      },
      {
        isVisable: true,
        name: "feeChallanValidity",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeChallanValidity",
      },
      {
        isVisable: true,
        name: "feeChallanValidityUpdate",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeChallanValidityUpdate",
      },
      {
        isVisable: true,
        name: "feeCampusBankLink",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeCampusBankLink",
      },
      
      
      {
        isVisable: true,
        name: "setupCollector",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "setupCollector",
      },
      {
        isVisable: true,
        name: "setupConcessionRemarks",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "setupConcessionRemarks",
      },
      {
        isVisable: true,
        name: "concessionRenew",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "concessionRenew",
      },
      {
        isVisable: true,
        name: "campusGradingMapping",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "campusGradingMapping",
      },
      {
        isVisable: true,
        name: "campusFailCriteriaMapping",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "campusFailCriteriaMapping",
      },
      {
        isVisable: true,
        name: "examSMSApproval",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examSMSApproval",
      },
      {
        isVisable: true,
        name: "customSms",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "customSms",
      },
      {
        isVisable: true,
        name: "approvesms",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "smsapproval",
      },
      // { isVisable: true, name: 'notification', svgPath: 'icon-layers', children: null, isHeader: false, route: 'notification' },
      {
        isVisable: true,
        name: "notificationApproval",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "notificationApproval",
      },

      {
        isVisable: true,
        name: "sessionDuration",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "sessionDuration",
      },
      {
        isVisable: true,
        name: "KinshipStudent",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "kinshipstd",
      },
      {
        isVisable: true,
        name: "ConcessStudent",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "concessstdd",
      },

      {
        isVisable: true,
        name: "BulkScholarship",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "concesskinsstdd",
      },

      {
        isVisable: true,
        name: "programTransfer",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "programTransfer",
      },
      {
        isVisable: true,
        name: "programTransferBulk",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "ProgramTransferBulk",
      },
      {
        isVisable: true,
        name: "smstostudent",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "smstostudent",
      },
      {
        isVisable: true,
        name: "setupExtraCourse",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "setupExtraCourse",
      },
    ],
  },
  //  {
  //     isVisable: true, name: 'exsetup', svgPath: icons.menu, isHeader: false, route: '#',
  //     children: [
  //         { isVisable: true, name: 'setupTerm', svgPath: 'icon-layers', children: null, isHeader: false, route: 'setupTerm' },
  //         { isVisable: true, name: 'setupPassStatus', svgPath: 'icon-layers', children: null, isHeader: false, route: 'setupPassStatus' },
  //         { isVisable: true, name: 'admissionSaleType', svgPath: 'icon-layers', children: null, isHeader: false, route: 'admissionSaleType' },
  //         { isVisable: true, name: 'feeTBLGrades', svgPath: 'icon-layers', children: null, isHeader: false, route: 'feeTBLGrades' },
  //         { isVisable: true, name: 'feeFeeStructureSingle', svgPath: 'icon-layers', children: null, isHeader: false, route: 'feeFeeStructureSingle' },
  //         { isVisable: true, name: 'attendanceAttendenceMaster', svgPath: 'settings', children: null, isHeader: false, route: 'attendanceAttendenceMaster' },
  //         { isVisable: true, name: 'feeSubInstallment', svgPath: 'icon-layers', children: null, isHeader: false, route: 'feeSubInstallment' },
  //         { isVisable: true, name: 'feeConfirmationEx', svgPath: 'icon-layers', children: null, isHeader: false, route: 'feeConfirmationEx' }

  //     ]
  //  },
  {
    isVisable: true,
    name: "qserup",
    svgPath: icons.hr,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "admission",
        svgPath: icons.admission,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "admissionBulitanSale",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionBulitanSale",
          },
          {
            isVisable: true,
            name: "admissionInquiry",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionInquiry",
          },
          {
            isVisable: true,
            name: "admissionAdmissionForm",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionAdmissionForm",
          },
          {
            isVisable: true,
            name: "admissionAdmissionFormBr",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionAdmissionFormBr",
          },

          //{ isVisable: true, name: 'StateChange', svgPath: 'icon-layers', children: null, isHeader: false, route: 'StateChange' },
          {
            isVisable: true,
            name: "admissionStudents",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionStudents",
          },
          {
            isVisable: true,
            name: "preAcademicInfo",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionPreAcademicInfo",
          },
          {
            isVisable: true,
            name: "OnlineFormApproval",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "onlineFormApproval",
          },
          {
            isVisable: true,
            name: "admissionReports",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "admissionReports",
          },
        ],
      },
      {
        isVisable: true,
        name: "registration",
        svgPath: icons.registration,
        isHeader: false,
        route: "#",
        children: [
          {
            isVisable: true,
            name: "registrationSectionCourseLink",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "registrationSectionCourseLink",
          },
          // { isVisable: true, name: 'enrollmentBulk', svgPath: 'icon-layers', children: null, isHeader: false, route: 'enrollmentBulk' },
          {
            isVisable: true,
            name: "enrollmentBatch",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "enrollmentBatch",
          },
          {
            isVisable: true,
            name: "microsoftStdPassword",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "microsoftStdPassword",
          },
          {
            isVisable: true,
            name: "ssatStudentData",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "ssatStudentData",
          },

          {
            isVisable: true,
            name: "sectionChange",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "sectionChange",
          },
          {
            isVisable: true,
            name: "sectionChangeBulk",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "sectionChangeBulk",
          },

          {
            isVisable: true,
            name: "campusTransferBulk",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "campusTransferBulk",
          },
          {
            isVisable: true,
            name: "classPromotion",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "classPromotion",
          },

          // { isVisable: true, name: 'transferClass', svgPath: 'icon-layers', children: null, isHeader: false, route: 'transferClass' },

          {
            isVisable: true,
            name: "struckoffReinstate",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "struckoffReinstate",
          },
          {
            isVisable: true,
            name: "enrollmentReverse",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "enrollmentReverse",
          },
          // { isVisable: true, name: 'registrationEmailProgram', svgPath: 'icon-layers', children: null, isHeader: false, route: 'registrationEmailProgram' },

          {
            isVisable: true,
            name: "enrolledReports",
            svgPath: "icon-layers",
            children: null,
            isHeader: false,
            route: "enrolledReports",
          },
          // { isVisable: true, name: 'CampusEmailMapping', svgPath: 'icon-layers', children: null, isHeader: false, route: 'CampusEmailMapping' },
        ],
      },
    ],
  },
  {
    isVisable: true,
    name: "fee",
    svgPath: icons.dollar,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "feeConfirmation",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeConfirmation",
      },
       {
        isVisable: true,
        name: "refundchallan",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "refundchallan",
      },
      {
        isVisable: true,
        name: "adhocChallanLink",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "adhocChallanLink",
      },
        {
        isVisable: true,
        name: "challanReversal",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "challanReversal",
      },
      {
        isVisable: true,
        name: "creditnotes",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "creditnotes",
      },
      {
        isVisable: true,
        name: "withdrawnConcessionReversal",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "withdrawnConcessionReversal",
      },
      {
        isVisable: true,
        name: "applyConcessionOnInstallment",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "applyConcessionOnInstallment",
      },
      {
        isVisable: true,
        name: "feeConfirmationEx",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeConfirmationEx",
      },
      {
        isVisable: true,
        name: "studentChallanDetail",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "admissionStudentFeeInfo",
      },
      {
        isVisable: true,
        name: "changeDueDate",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "changeDueDate",
      },
      {
        isVisable: true,
        name: "feeReverseConcessionList",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeReverseConcessionList",
      },
      {
        isVisable: true,
        name: "feeExemption",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "fullfeeChallan",
      },
      {
        isVisable: true,
        name: "feeExemptionManually",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeExemptionManually",
      },
      {
        isVisable: true,
        name: "mulitplesubinstallments",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "mulitplesubinstallments",
      },

      {
        isVisable: true,
        name: "customChallan",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "customChallan",
      },
      {
        isVisable: true,
        name: "educationChallan",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "educationChallan",
      },

      {
        isVisable: true,
        name: "sectionFine",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "sectionFine",
      },
      {
        isVisable: true,
        name: "feeChallanSearch",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeChallanSearch",
      },
      {
        isVisable: true,
        name: "previousFee",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "previousFee",
      },
      {
        isVisable: true,
        name: "feeStudentChallanPaidList",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeStudentChallanPaidList",
      },
      {
        isVisable: true,
        name: "feeApplyConcessionBulk",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeApplyConcessionBulk",
      },
      // { isVisable: true, name: 'feeApplyConcession', svgPath: 'icon-layers', children: null, isHeader: false, route: 'feeApplyConcession' },
      // { isVisable: true, name: 'feeApplyScholarship', svgPath: 'icon-layers', children: null, isHeader: false, route: 'feeApplyScholarship' },
      // { isVisable: true, name: 'singleConcession', svgPath: 'icon-layers', children: null, isHeader: false, route: 'singleConcession' },
      {
        isVisable: true,
        name: "challanCancel",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "challanCancel",
      },
      {
        isVisable: true,
        name: "changePaidDate",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "changePaidDate",
      },
      {
        isVisable: true,
        name: "attendanceFineGenerate",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "attendanceFineGenerate",
      },
      {
        isVisable: true,
        name: "applyBulkChallanPre",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "applyBulkChallanPre",
      },

      // { isVisable: true, name: 'studentFeeDetailDescription', svgPath: 'icon-layers', children: null, isHeader: false, route: 'studentFeeDetailDescription' },
      {
        isVisable: true,
        name: "concessionReports",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "concessionReports",
      },
      {
        isVisable: true,
        name: "financeData",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "financeData",
      },
      {
        isVisable: true,
        name: "feeReports",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "feeReports",
      },
      {
        isVisable: true,
        name: "financeReports",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "financeReports",
      },
    ],
  },
  {
    isVisable: true,
    name: "attendance",
    svgPath: icons.attendance,
    isHeader: false,
    route: "#",
    children: [
      //{ isVisable: true, name: 'attendanceBulk', svgPath: 'settings', children: null, isHeader: false, route: 'attendanceBulk' },
      {
        isVisable: true,
        name: "attendanceTeacherUser",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "attendanceTeacherUser",
      },

      {
        isVisable: true,
        name: "attendanceBulkDetail",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "attendanceBulkDetail",
      },
      {
        isVisable: true,
        name: "attendanceApproval",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "attendanceApproval",
      },
      {
        isVisable: true,
        name: "attendanceApprovalRemove",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "attendanceApprovalRemove",
      },
      {
        isVisable: true,
        name: "smartattendence",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "smartAttendence",
      },

      // { isVisable: true, name: 'dayClose', svgPath: 'settings', children: null, isHeader: false, route: 'dayClose' },
      {
        isVisable: true,
        name: "markDayEnd",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "markDayEnd",
      },
      {
        isVisable: true,
        name: "dailyAttendanceStatus",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "dailyAttendanceStatus",
      },
      {
        isVisable: true,
        name: "leaveManagement",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "leaveManagement",
      },
      // { isVisable: true, name: 'leaveApproval', svgPath: 'settings', children: null, isHeader: false, route: 'leaveApproval' },
      {
        isVisable: true,
        name: "attendanceReports",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "attendanceReports",
      },
    ],
  },
  // {
  //     isVisable: true, name: 'uCreation', svgPath: icons.book, isHeader: false, route: '#',
  //     children: [
  //         { isVisable: true, name: 'uCreation', svgPath: 'icon-layers', children: null, isHeader: false, route: 'UserCreation' },

  //     ]
  // },
  {
    isVisable: true,
    name: "examination",
    svgPath: icons.examination,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "examinationExamType",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examinationExamType",
      },
      //  { isVisable: true, name: 'examinationExamSchedule', svgPath: 'icon-layers', children: null, isHeader: false, route: 'examinationExamSchedule' },
      {
        isVisable: true,
        name: "examBulk",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examBulk",
      },
      {
        isVisable: true,
        name: "examApproval",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examApproval",
      },
      //{ isVisable: true, name: 'examdeletion', svgPath: 'icon-layers', children: null, isHeader: false, route: 'examDeletion' },

      {
        isVisable: true,
        name: "examUnApproval",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examUnApproval",
      },
      {
        isVisable: true,
        name: "examUpdationlist2",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examUpdationList",
      },

      {
        isVisable: true,
        name: "seatingPlanDateSheetList",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "seatingPlanDateSheetList",
      },
      {
        isVisable: true,
        name: "seatingPlanDateSheetDetailList",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "seatingPlanDateSheetDetailList",
      },
      {
        isVisable: true,
        name: "SeatingPlanStudent",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "SeatingPlanStudent",
      },
      {
        isVisable: true,
        name: "examinationReports",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examinationReports",
      },
    ],
  },
  {
    isVisable: true,
    name: "Assessment",
    svgPath: icons.examination,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "levelDefinition",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "levelDefinition",
      },
      {
        isVisable: true,
        name: "LevelProgramClassMap",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "LevelProgramClassMap",
      },

      {
        isVisable: true,
        name: "assessmentCategory",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "assessmentCategory",
      },
      {
        isVisable: true,
        name: "assessmentType",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "assessmentType",
      },

      //  { isVisable: true, name: 'examinationExamSchedule', svgPath: 'icon-layers', children: null, isHeader: false, route: 'examinationExamSchedule' },
      {
        isVisable: true,
        name: "AssessmentSectionMap",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "AssessmentSectionMap",
      },
      {
        isVisable: true,
        name: "assessmentSchemeDefinition",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "assessmentSchemeDefinition",
      },

      {
        isVisable: true,
        name: "assessmentScheduling",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "assessmentScheduling",
      },
      // {
      //     isVisable: true,
      //     name: "admissionRollNoSlip",
      //     svgPath: "icon-layers",
      //     children: null,
      //     isHeader: false,
      //     route: "admissionRollNoSlip",
      // },

      {
        isVisable: true,
        name: "assessmentSchedule",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "assessmentSchedule",
      },
      {
        isVisable: true,
        name: "AssessmentReport",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "AssessmentReport",
      },
    ],
  },
  {
    isVisable: true,
    name: "examination2",
    svgPath: icons.examSchedule,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "examinationExamSchedule",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examinationExamSchedule",
      },
      {
        isVisable: true,
        name: "examScheduleDetail",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examScheduleDetail",
      },

      {
        isVisable: true,
        name: "examApproval",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examApprovalexam2",
      },
      {
        isVisable: true,
        name: "examUnApproval",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examUnApprovalexam2",
      },
      {
        isVisable: true,
        name: "examdeletion",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examDeletion",
      },

      {
        isVisable: true,
        name: "examinationReports2",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examinationReports2",
      },
      // { isVisable: true, name: 'examinationReports', svgPath: 'icon-layers', children: null, isHeader: false, route: 'ExaminationReportsEx' }
      {
        isVisable: true,
        name: "examUpdationlist2",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "examUpdationListES",
      },
      // { isVisable: true, name: 'examdeletion', svgPath: 'icon-layers', children: null, isHeader: false, route: 'examDeletion2' },
    ],
  },
  {
    isVisable: true,
    name: "timetable",
    svgPath: icons.timetable,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "timeTableTimeTable",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "timeTableTimeTable",
      },
      {
        isVisable: true,
        name: "timetableclose",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "timetableclose",
      },
      {
        isVisable: true,
        name: "timeTableTimeTableMerge",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "timetableMerge",
      },
      // { isVisable: true, name: 'dayOff', svgPath: 'settings', children: null, isHeader: false, route: 'dayOff' },
      {
        isVisable: true,
        name: "TimeTableDayOffBulkList",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "TimeTableDayOffBulkList",
      },
      {
        isVisable: true,
        name: "RemoveDayOffBulkList",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "RemoveDayOffBulkList",
      },

      {
        isVisable: true,
        name: "Sectionincharge",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "Sectionincharge",
      },
    ],
  },
  {
    isVisable: true,
    name: "transportation",
    svgPath: icons.transport,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "routeInfo",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "routeInfo",
      },
      {
        isVisable: true,
        name: "routeDetailInfo",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "routeDetailInfo",
      },
      {
        isVisable: true,
        name: "vehicleInfo",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "vehicleInfo",
      },
      {
        isVisable: true,
        name: "routeStudentLink",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "routeStudentLink",
      },
      {
        isVisable: true,
        name: "transportationReports",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "transportationReports",
      },
    ],
  },
  {
    isVisable: true,
    name: "academiccalendarmain",
    svgPath: icons.calendar,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "academiccalendarmaster",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "academicCalendarMaster",
      },
      {
        isVisable: true,
        name: "events",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "events",
      },
      {
        isVisable: true,
        name: "academiccalendar",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "academicCalendar",
      },
      // {
      //     isVisable: true,
      //     name: "academiccalendar",
      //     svgPath: "settings",
      //     children: null,
      //     isHeader: false,
      //     route: "academicCalendar",
      // },

      {
        isVisable: true,
        name: "calendarConfirmation",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "calendarConfirmation",
      },
      {
        isVisable: true,
        name: "academicCalendarReport",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "academicCalendarReport",
      },
      {
        isVisable: true,
        name: "academicSectionMap",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "academicSectionMap",
      },

      {
        isVisable: true,
        name: "academicCalendarType",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "academicCalendarType",
      },
      {
        isVisable: true,
        name: "holidaytype",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "holidaytype",
      },
      {
        isVisable: true,
        name: "holidays",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "holidays",
      },
      {
        isVisable: true,
        name: "elChapters",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "elChapters",
      },
      {
        isVisable: true,
        name: "boards",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "Boards",
      },
      // { isVisable: true, name: 'videos', svgPath: 'icon-layers', children: null, isHeader: false, route: 'Videos' },
      {
        isVisable: true,
        name: "topics",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "Topics",
      },
      {
        isVisable: true,
        name: "topicsVideo",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "TopicsVideo",
      },
      // { isVisable: true, name: 'answers', svgPath: 'icon-layers', children: null, isHeader: false, route: 'MCQsAnswers' },
      {
        isVisable: true,
        name: "boardProgramClassCourseLink",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "BoardProgramClassCourseLink",
      },
    ],
  },

  {
    isVisable: true,
    name: "board",
    svgPath: icons.board,
    isHeader: false,
    route: "#",
    children: [
      // { isVisable: true, name: 'boardCampus', svgPath: 'icon-layers', children: null, isHeader: false, route: 'boardCampus' },
      // { isVisable: true, name: 'boardCampusStudentLink', svgPath: 'icon-layers', children: null, isHeader: false, route: 'boardCampusStudentLink' },
      {
        isVisable: true,
        name: "SessionBoardExamTypeList",
        svgPath: "icon-layer",
        children: null,
        isHeader: false,
        route: "SessionBoardExamTypeList",
      },
      {
        isVisable: true,
        name: "returnType",
        svgPath: "icon-layer",
        children: null,
        isHeader: false,
        route: "returnTypeList",
      },
      // { isVisable: true, name: 'boardFee', svgPath: 'icon-layer', children: null, isHeader: false, route: 'boardFee' },
      //{ isVisable: true, name: 'sessionBoardFee', svgPath: 'icon-layer', children: null, isHeader: false, route: 'sessionBoardFeeList' },
      //{ isVisable: true, name: 'BoardProgramCampusList', svgPath: 'icon-layer', children: null, isHeader: false, route: 'BoardProgramCampusList' },
      {
        isVisable: true,
        name: "BoardRegistrationCode",
        svgPath: "icon-layer",
        children: null,
        isHeader: false,
        route: "registrationCode",
      },
      {
        isVisable: true,
        name: "BoardStudentBoardLinkList",
        svgPath: "icon-layer",
        children: null,
        isHeader: false,
        route: "BoardStudentBoardLinkList",
      },
      {
        isVisable: true,
        name: "boardStudentRegistrationNo",
        svgPath: "icon-layer",
        children: null,
        isHeader: false,
        route: "boardStudentRegistrationNo",
      },
      {
        isVisable: true,
        name: "boardUniversityExamEntry",
        svgPath: "icon-layer",
        children: null,
        isHeader: false,
        route: "boardUniversityExamEntry",
      },
      {
        isVisable: true,
        name: "BoardUniversitySearchStudent",
        svgPath: "icon-layer",
        children: null,
        isHeader: false,
        route: "boardUniversitySearchStudent",
      },

      // "BoarUniversitySearchStudent": "Boar/University Search Student",
      {
        isVisable: true,
        name: "boardUniversityRollNo",
        svgPath: "icon-layer",
        children: null,
        isHeader: false,
        route: "boardUniversityRollNo",
      },
      {
        isVisable: true,
        name: "boardUniversityResultCard",
        svgPath: "icon-layer",
        children: null,
        isHeader: false,
        route: "boardUniversityResultCard",
      },
    ],
  },

  {
    isVisable: true,
    name: "teachermng",
    svgPath: icons.clipboard,
    isHeader: false,
    route: "#",
    children: [
      // { isVisable: true, name: 'teacherDashboard', svgPath: 'settings', children: null, isHeader: false, route: 'teacherDashboard' },
      {
        isVisable: true,
        name: "viewTimeTable",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "viewTimeTable",
      },
      {
        isVisable: true,
        name: "attendanceTeacher",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "attendanceTeacher",
      },
      {
        isVisable: true,
        name: "attendanceTeacherBulk",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "attendanceTeacherBulk",
      },

      {
        isVisable: true,
        name: "teacherAttendanceReport",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "teacherAttendanceReport",
      },
      {
        isVisable: true,
        name: "teacherExam",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "teacherExam",
      },

      {
        isVisable: true,
        name: "teacherExam2",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "teacherExam2",
      },

      // { isVisable: true, name: 'academiccalendar', svgPath: 'settings', children: null, isHeader: false, route: 'academicCalendar' },
      // { isVisable: true, name: 'academiccalendarmaster', svgPath: 'settings', children: null, isHeader: false, route: 'academicCalendarMaster' },

      // { isVisable: true, name: 'academicCalendarType', svgPath: 'settings', children: null, isHeader: false, route: 'academicCalendarType' },
      // { isVisable: true, name: 'holidaytype', svgPath: 'settings', children: null, isHeader: false, route: 'holidaytype' },
      // { isVisable: true, name: 'holidays', svgPath: 'settings', children: null, isHeader: false, route: 'holidays' },

      {
        isVisable: true,
        name: "studentRoster",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "studentRoster",
      },
      {
        isVisable: true,
        name: "attendanceRegister",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "attendanceRegister",
      },
      {
        isVisable: true,
        name: "studentAttendance",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "studentAttendance",
      },
    ],
  },
  {
    isVisable: true,
    name: "el",
    svgPath: icons.el,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "question",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "MCQsQuestionList",
      },

      {
        isVisable: true,
        name: "chapterLinks",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "ChapterLinks",
      },

      // { isVisable: true, name: 'elModelPapersQuestions', svgPath: 'icon-layers', children: null, isHeader: false, route: 'elModelPapersQuestions' },
      // { isVisable: true, name: 'elQuestions', svgPath: 'icon-layers', children: null, isHeader: false, route: 'elQuestions' },
      // { isVisable: true, name: 'elTopics', svgPath: 'icon-layers', children: null, isHeader: false, route: 'elTopics' }
    ],
  },
  {
    isVisable: true,
    name: "hr",
    svgPath: icons.group,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "humanResourceDepartments",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "humanResourceDepartments",
      },
      {
        isVisable: true,
        name: "humanResourceDesignations",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "humanResourceDesignations",
      },
      {
        isVisable: true,
        name: "humanResourceStaff",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "humanResourceStaff",
      },
      {
        isVisable: true,
        name: "Teacherhod",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "Teacherhod",
      },
      {
        isVisable: true,
        name: "teacherEvaluation",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "teacherEvaluation",
      },

      {
        isVisable: true,
        name: "UpdateMicrosoftPass",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "updmicropass",
      },
      {
        isVisable: true,
        name: "staffCourse",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "staffCourse",
      },
      {
        isVisable: true,
        name: "staffProfile",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "staffProfile",
      },
    ],
  },
  {
    isVisable: true,
    name: "role",
    svgPath: icons.userfolder,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "RolePrevilages",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "roleprevilages",
      },
      {
        isVisable: true,
        name: "UserLog",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "userLog",
      },
      {
        isVisable: true,
        name: "SecurityClaims",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "securityclaims",
      },
      {
        isVisable: true,
        name: "SectionRightLink",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "sectionRightLink",
      },
      {
        isVisable: true,
        name: "MaskRightLink",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "maskRightLink",
      },
      {
        isVisable: true,
        name: "createStudentUser",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "registrationStudentUserGen",
      },
      {
        isVisable: true,
        name: "userList",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "userlist",
      },
      {
        isVisable: true,
        name: "listRoles",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "roleList",
      },
    ],
  },
  {
    isVisable: true,
    name: "ulog",
    svgPath: icons.selectedfile,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: true,
        name: "attendanceHistory",
        svgPath: "icon-layers",
        children: null,
        isHeader: false,
        route: "attendanceHistory",
      },
    ],
  },
  {
    isVisable: true,
    name: "quiz",
    svgPath: icons.quiz,
    isHeader: false,
    route: "#",
    children: [
      {
        isVisable: false,
        name: "cityConfigurationQuiz",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "cityConfigurationQuiz",
      },
      {
        isVisable: true,
        name: "leagueConfigurationQuiz",
        svgPath: "settings",
        children: null,
        isHeader: false,
        route: "leagueConfigurationQuiz",
      },
    ],
  },
];

export class PopulateMenu {
  private user: IUser;
  private auth: AuthenticationService;
  private menu = [];

  constructor(providedUser: IUser) {
    this.user = providedUser;
    this.auth = new AuthenticationService(Store);
    this.menu = providedMenu;

    if (!this.isInAdminRole) {
      this.menu
        .filter((e) => e.route == "#")
        .forEach((element) => {
          this.processMenu(element);
        });
    }
  }

  private get isInAdminRole() {
    return (
      this.user.authenticated &&
      this.auth.satisfies(this.user, [SecurityRoleClaims.Admin])
    );
  }

  processMenu(item: IMenu) {
    if (item.children) {
      item.children.forEach((element) => {
        this.processMenu(element);
      });
      item.isVisable = this.hasChildrenVisible(item);
    } else {
      item.isVisable = this.foundInRoule(item.route);
    }
  }

  private foundInRoule(value) {
    return this.user.claims[value] != undefined;
  }

  private hasChildrenVisible(item: IMenu) {
    var found: boolean = false;
    item.children.forEach((element) => {
      if (element.isVisable == true) {
        found = true;
      }
    });
    return found;
  }
}
