import { CustomSms } from "../application/views/Message/Sms/list";
import { Franchise } from "../application/views/Setup/Franchise/list/index";

export const RouteNames = {
  forbidden: "403",
  admin: {
    home: "admin.home",
    dashboard: "admin.dashboard",
  },
  home: "home",
  login: {
    home: "login",
    verify: "verify",
  },
  profile: "profile",
  root: "root",
  search: "search",
  signup: "signup",

  Views: {
    helper: "helper",
    admissionAdmissionForm: "admissionAdmissionForm",
    admissionAdmissionFormEx: "admissionAdmissionFormEx",
    admissionAdmissionFormBr: "admissionAdmissionFormBr",
    bulkCopyProgramDetail: "bulkCopyProgramDetail",
    manageUserEx: "manageUserEx",
    readRoleEx: "readRoleEx",
    createRoleEx: "createRoleEx",
    updateRoleEx: "updateRoleEx",
    roleList: "roleList",
    admissionBulitanSale: "admissionBulitanSale",
    admissionInquiry: "admissionInquiry",
    admissionEligibilityCriteria: "admissionEligibilityCriteria",
    admissionSaleType: "admissionSaleType",
    programFeeAdjustment: "programFeeAdjustment",
    transferClass: "transferClass",

    admissionStudents: "admissionStudents",
    admissionPreAcademicInfo: "admissionPreAcademicInfo",
    studentprofile: "studentprofile",
    ProgramTransfer: "ProgramTransfer",
    ProgramTransferBulk: "ProgramTransferBulk",
    CampusTransferBulk: "CampusTransferBulk",
    StateChange: "StateChange",
    sessionDuration: "sessionDuration",
    admissionStudentsImage: "admissionStudentsImage",
    attendanceAttendanceDetail: "attendanceAttendanceDetail",
    attendanceAttendenceMaster: "attendanceAttendenceMaster",
    attendanceAttendenceStatus: "attendanceAttendenceStatus",
    quizDashboard: "quizDashboard",
    attendanceAttendenceDashboard: "attendanceAttendenceDashboard",
    attendanceAttendenceDashboard2: "attendanceAttendenceDashboard2",
    admissionDuplicateRemove: "admissionDuplicateRemove",
    elMigration: "elMigration",
    elUpdation: "elUpdation",
    kinshipstd: "kinshipstd",
    concessstd: "concessstd",
    concesskinsstdd: "concesskinsstdd",
    Timetableclose: "Timetableclose",
    concessionDashboard: "concessionDashboard",
    admissionDashboard: "admissionDashboard",
    admissionComaprisonDashboard: "admissionComaprisonDashboard",
    assessment: "assessment",
    assessmentCategory: "assessmentCategory",
    assessmentSchedule: "assessmentSchedule",
    admissionComaprisonDashboardCampusWise: "admissionComaprisonDashboardCampusWise",
    admissionComaprisonDashboardCampusWiseClone: "admissionComaprisonDashboardCampusWiseClone",
    creditnotes: "creditnotes",
    studentfeedback: "studentfeedback",
    withdrawnConcessionReversal: "withdrawnConcessionReversal",
    applyConcessionOnInstallment: "applyConcessionOnInstallment",
    notificationDashboard: "notificationDashboard",
    notificationDash: "NotificationDash",
    SurveyDash: "SurveyDash",
    SurveyDashDecember: "SurveyDashDecember",
    SurveyDashApril: "SurveyDashApril",
    SurveyDashDecember22: "SurveyDashDecember22",
    SurveyDashjan22: "SurveyDashjan22",
    SurveyDashJuly23Statistics: "SurveyDashJuly23Statistics",
    SurveyDashJune24Statistics: "SurveyDashJune24Statistics",
    SurveyDashJan25Statistics: "SurveyDashJan25Statistics", 
    SurveyDashJan26Statistics:"SurveyDashJan26Statistics",
    SurveyDashEbooks24Statistics: "SurveyDashEbooks24Statistics",
    SurveyDashjuly23: "SurveyDashjuly23",
    SurveyDashjune24: "SurveyDashjune24",
    SurveyDashEbook24: "SurveyDashEbook24",
    SurveyDashboardJanuary24: "SurveyDashboardJanuary24",
    SurveyDashboardJanuary26: "SurveyDashboardJanuary26",
    SurveyDashboardJanuary25: "SurveyDashboardJanuary25",
    LevelProgramClassMap: "LevelProgramClassMap",
    AssessmentSectionMap: "AssessmentSectionMap",

    assessmentScheduling: "AssessmentScheduling",
    admissionRollNoSlip: "Admission / Roll No Slip",
    surveyDashboard: "surveyDashboard",
    feePaidDashboard: "feePaidDashboard",
    revenueDashboard: "revenueDashboard",
    comparisonDashboard: "comparisonDashboard",
    attendanceBulk: "attendanceBulk",
    attendanceTeacher: "attendanceTeacher",
    attendanceTeacherBulk: "attendanceTeacherBulk",
    dayClose: "dayClose",
    markDayEnd: "markDayEnd",
    DailyAttendanceStatus: "dailyAttendanceStatus",

    attendanceTeacherUser: "attendanceTeacherUser",
    smstostudent: "smstostudent",

    attendanceBulkDetail: "attendanceBulkDetail",
    leaveManagement: "leaveManagement",
    leaveManagementtest: "leaveManagementtest",
    leaveApproval: "leaveApproval",
    MaskRightLink: "MaskRightLink",
    boardStudentRegistrationNo: "boardStudentRegistrationNo",
    boardUniversityExamEntry: "boardUniversityExamEntry",
    boardUniversitySearchStudent: "boardUniversitySearchStudent",
    onlineFormApproval: "onlineFormApproval",
    boardUniversityRollNo: "boardUniversityRollNo",
    boardUniversityResultCard: "boardUniversityResultCard",

    boardCampus: "boardCampus",
    boardCampusStudentLink: "boardCampusStudentLink",
    returnTypeList: "returnTypeList",
    sessionBoardFeeList: "sessionBoardFeeList",
    boardFee: "boardFee",
    registrationCode: "registrationCode",
    financeData: "financeData",

    attendanceApproval: "attendanceApproval",
    attendanceApprovalRemove: "attendanceApprovalRemove",
    attendanceHistory: "attendanceHistory",
    struckoffReinstate: "struckoffReinstate",
    pushNotification: "pushNotification",
    pushNotificationCampus: "pushNotificationCampus",

    // examinationCampusGradingPolicyLink: 'examinationCampusGradingPolicyLink',
    examBulk: "examBulk",
    examScheduleDetail: "examScheduleDetail",
    examinationExamDetail: "examinationExamDetail",
    examinationExamMaster: "examinationExamMaster",
    examinationExamSectionLink: "examinationExamSectionLink",
    examinationExamType: "examinationExamType",
    LevelDefinition: "LevelDefinition",
    AssessmentReport: "AssessmentReport",
    examinationGradingPolicy: "examinationGradingPolicy",
    gradingPolicyBulk: "gradingPolicyBulk",
    examinationExamSchedule: "examinationExamSchedule",
    failCriteria: "failCriteria",
    teacherEvaluation: "teacherEvaluation",

    gradingCriteria: "gradingCriteria",
    campusFailCriteriaMapping: "campusFailCriteriaMapping",
    campusGradingMapping: "campusGradingMapping",

    examApproval: "examApproval",
    examApprovalexam2: "",

    examSMSApproval: "examSMSApproval",

    examDeletion: "examDeletion",
    examDeletion2: "examDeletion2",
    SmartAttendance: "SmartAttendance",

    examUnApproval: "examUnApproval",
    examUnApprovalexam2: "examUnApprovalexam2",

    examResultApproval: "examResultApproval",
    teacherExam: "teacherExam",
    teacherExam2: "teacherExam2",

    feeBank: "feeBank",
    feeCampusBankLink: "feeCampusBankLink",
    adhocChallanLink:"adhocChallanLink",
    feeCampusChallanNoteLink: "feeCampusChallanNoteLink",
    feeChallanNote: "feeChallanNote",
    feeChallanType: "feeChallanType",
    feeChallanValidity: "feeChallanValidity",
    feeConcession: "feeConcessionBulk",
    feeConcessionBulk: "feeConcession",
    feeApplyConcessionBulk: "feeApplyConcessionBulk",
    applyBulkChallanPre: "applyBulkChallanPre",
    feeApplyConcession: "feeApplyConcession",
    feeConfirmation: "feeConfirmation",
    challanReversal:"challanReversal",
    refundchallan:"refundchallan",
    feeChallanSearch: "feeChallanSearch",
    changePaidDate: "changePaidDate",
    changeDueDate: "changeDueDate",
    //singleConcession: 'singleConcession',
    previousFee: "previousFee",
    feeApplyScholarship: "feeApplyScholarship",
    feeConcessionDetail: "feeConcessionDetail",
    feeContinuationPolicy: "feeContinuationPolicy",
    feeFeeActivity: "feeFeeActivity",
    customChallan: "customChallan",
    educationChallanList: "educationChallanList",

    feeFeeHead: "feeFeeHead",
    ClassTransfer: "ClassTransfer",
    setupConcessionRemarks: "setupConcessionRemarks",
    feeFeeStructure: "feeFeeStructure",
    feeFeeStructureSingle: "feeFeeStructureSingle",
    feeFeeStructureApproval: "feeFeeStructureApproval",
    minimumPaidDate: "minimumPaidDate",
    feeFeeStructureDetail: "feeFeeStructureDetail",
    feeScholarshipCriteria: "feeScholarshipCriteria",
    feeTBLGrades: "feeTBLGrades",
    feeStudentChallan: "feeStudentChallan",
    feeStudentChallanPaidList: "feeStudentChallanPaidList",
    concessionRenew: "concessionRenew",
    feeExemptionManually: "feeExemptionManually",
    multiplesubinstallments: "multiplesubinstallments",
    SessionBoardExamTypeList: "SessionBoardExamTypeList",
    BoardProgramCampusList: "BoardProgramCampusList",
    BoardStudentBoardLinkList: "BoardStudentBoardLinkList",
    FeeChallanValidityUpdate: "FeeChallanValidityUpdate",
    feeReverseConcessionList: "feeReverseConcessionList",
    examUpdationList: "examUpdationList",
    examUpdationListES: "examUpdationListES",

    StudentFeeDetailDescription: "StudentFeeDetailDescriptionList",
    challanCancel: "ChallanCancel",
    sectionFine: "SectionFine",
    // fullFee: "fullFee",
    // feeStudentFeeStructure: 'feeStudentFeeStructure',
    attendanceFineGenerate: "attendanceFineGenerate",
    feeSubInstallment: "feeSubInstallment",
    fullfeeChallan: "fullfeeChallan",
    humanResourceDepartments: "humanResourceDepartments",
    updmicropass: "updmicropass",

    humanResourceDesignations: "humanResourceDesignations",
    humanResourceStaff: "humanResourceStaff",
    staffCourse: "staffCourse",
    Teacherhod: "Teacherhod",
    Sectionincharge: "Sectionincharge",
    profileStaff: "profileStaff",
    registrationCourse: "registrationCourse",
    registrationEmailProgram: "registrationEmailProgram",
    emailTemplate: "emailTemplate",
    CampusEmailMapping: "CampusEmailMapping",

    // registrationEnrollments: 'registrationEnrollments',
    enrollmentBulk: "enrollmentBulk",
    sectionChange: "sectionChange",
    sectionChangeBulk: "sectionChangeBulk",
    classPromotion: "classPromotion",
    studentUserGen: "registrationstudentUserGen",
    registrationProgramCourseLink: "registrationProgramCourseLink",
    enrollmentReverse: "enrollmentReverse",
    registrationEnrollmentBulkWithoutPaidList:
      "registrationEnrollmentBulkWithoutPaidList",
    registrationEnrollmentBulkWithoutPaidListEx:
      "registrationEnrollmentBulkWithoutPaidListEx",

    registrationSectionCourseLink: "registrationSectionCourseLink",
    registrationSections: "registrationSections",
    registrationStudentUserGen: "registrationStudentUserGen",
    setupAddress: "setupAddress",
    setupAdmissionType: "setupAdmissionType",
    setupBloodGroup: "setupBloodGroup",
    setupBoard: "setupBoard",
    setupBoardType: "setupBoardType",
    setupBuilding: "setupBuilding",
    setupBuildingAddressLink: "setupBuildingAddressLink",
    setupBusinessGroup: "setupBusinessGroup",
    setupBusinessUnit: "setupBusinessUnit",
    assessmentType: "assessmentType",
    assessmentSchemeDefinition: "assessmentSchemeDefinition",
    setupCampus: "setupCampus",
    setupCampusBuildingLink: "setupCampusBuildingLink",
    setupCampusProgramLink: "setupCampusProgramLink",
    setupCity: "setupCity",
    setupClass: "setupClass",
    setupCollector: "setupCollector",
    setupCountry: "setupCountry",
    setupGender: "setupGender",
    setupInstitution: "setupInstitution",
    setupInstitutionType: "setupInstitutionType",
    setupMedium: "setupMedium",
    dashboardSurvey: "dashboardSurvey",
    dashboardSurveydetail: "dashboardSurveydetail",
    setupMonth: "setupMonth",
    setupNationality: "setupNationality",
    setupPossession: "setupPossession",
    setupPossessionType: "setupPossessionType",
    setupProgram: "setupProgram",
    setupProgramDetails: "setupProgramDetails",
    setupProvince: "setupProvince",
    setupReligion: "setupReligion",
    setupRoom: "setupRoom",
    setupRoomBuildingLink: "setupRoomBuildingLink",
    setupRoomType: "setupRoomType",
    setupSection: "setupSection",
    setupSession: "setupSession",
    setupBatch: "setupBatch",
    setupShift: "setupShift",
    setupSubCity: "setupSubCity",
    setupStatus: "setupStatus",
    setupTerm: "setupTerm",
    setupZone: "setupZone",
    setupZoneCityLink: "setupZoneCityLink",
    setupGroup: "setupGroup",
    setupPassStatus: "setupPassStatus",
    setupDegree: "setupDegree",
    timeTableSlots: "timeTableSlots",
    timeTableSlotTimings: "timeTableSlotTimings",
    timeTableTimeTable: "timeTableTimeTable",
    substituteTimeTable: "substituteTimeTable",
    userlist: "userlist",
    timetableMerge: "timetableMerge",
    timeTableTimeTableBulk: "timeTableTimeTableBulk",
    franchise: "franchise",
    TimeTableDayOffBulkList: "TimeTableDayOffBulkList",
    RemoveDayOffBulkList: "RemoveDayOffBulkList",
    dayOff: "dayOff",
    elChapters: "elChapters",
    MCQsQuestionList: "MCQsQuestionList",
    Boards: "Boards",
    Videos: "Videos",
    Topics: "Topics",
    TopicsVideo: "TopicsVideo",
    BoardProgramClassCourseLinkList: "BoardProgramClassCourseLinkList",
    elModelPapers: "elModelPapers",
    elModelPapersQuestions: "elModelPapersQuestions",
    elQuestions: "elQuestions",
    elTopics: "elTopics",
    MCQsAnswers: "MCQsAnswers",
    ChapterLinksList: "ChapterLinksList",

    admissionReports: "admissionReports",
    feeReports: "feeReports",
    financeReports:"financeReports",
    concessionReports: "concessionReports",
    attendanceReports: "attendanceReports",
    enrolledReports: "enrolledReports",
    examinationReports: "examinationReports",
    examinationReports2: "examinationReports2",
    examinationReportsEx: "examinationReportsEx",

    transportationReports: "transportationReports",
    customFee: "customFee",
    enrollmentBatch: "enrollmentBatch",
    microsoftStdPassword: "microsoftStdPassword",
    ssatStudentData: "ssatStudentData",
    admissionStudentFeeInfo: "admissionStudentFeeInfo",
    //Transportation//
    vehicleInfo: "vehicleInfo",
    routeStopLink: "routeStopLink",
    routeInfo: "routeInfo",
    busStopInfo: "busStopInfo",
    routeStudentLink: "routeStudentLink",
    routeDetailInfo: "routeDetailInfo",
    feeConfirmationEx: "feeConfirmationEx",
    // teacherDashBoard: "teacherDashBoard",
    teacherTimeTable: "viewTimeTable",
    academicholidaytype: "academicholidaytype",
    academicholidays: "academicholidays",
    academicevents: "academicevents",
    calendarConfirmation: "calendarConfirmation",
    setupExtraCourse: "setupExtraCourse",

    teacherAttendanceReport: "teacherAttendanceReport",
    teacherExamReport: "academicCalendar",
    academicCalendarNew: "academicCalendarNew",
    academicCalendarType: "academicCalendarType",
    academicCalendarMaster: "academicCalendarMaster",
    academicCalendarReport: "academicCalendarReport",
    academicSectionMap: "academicSectionMap",
    studentRoster: "studentRoster",
    AttendanceRegister: "AttendanceRegister",
    StudentAttendance: "StudentAttendance",
    RolePrevilages: "RolePrevilages",
    UserLog: "UserLog",
    SecurityClaimsUpd: "SecurityClaimsUpd",
    SectionRightLink: "SectionRightLink",

    // UserRecord:'user'

    //Messages
    customSms: "customSms",
    smsapproval: "smsapproval",
    notification: "notification",
    NotificationApproval: "NotificationApproval",
    messageSMSAPIList: "messageSMSAPIList",
    messageTemplate: "messageTemplate",

    //migrate
    AttendancePercentage: "AttendancePercentage",

    //seating plan

    seatingPlanDateSheetList: "seatingPlanDateSheetList",
    seatingPlanDateSheetDetailList: "seatingPlanDateSheetDetailList",
    SeatingPlanStudent: "SeatingPlanStudent",

    //UserCreation

    UserCreation: "UserCreation",
    cityConfigurationQuiz: "cityConfigurationQuiz",
    leagueConfigurationQuiz: "leagueConfigurationQuiz",
  },
};
